Shopify/shopify_app

lib/generators/shopify_app/templates/app/views/home/index.html.erb

Changing `.blank?` to `.none?` so that the proper table shows on the default index page when there are no products or no orders.
Changes this : 
... to this : 
@jamesmacaulay @silverstreaked

Fix display when there are no products / orders

---

index.md

There was a typo in the ShopifySessionRepository.store example on the
Github pages. The same typo used to exist in the Readme but was fixed in
83fdda7.

Fix typo in the ShopifySessionRepository.store example

---

lib/generators/shopify_app/templates/config/initializers/shopify_session_repository.rb

I got stuck at this part because I implemented the (old) ``ShopifySessionRepository.storage = Shop`` instead of ``ShopifySessionRepository.storage = 'Shop'`` that fixed #103 in #112.
Thought this might help some other people too.

Update shopify_session_repository.rb instructions

---

lib/shopify_app/configuration.rb
lib/shopify_app/version.rb
test/config/development_config_file.yml
test/config/other_config_file.yml
test/config/shopify_app.yml
test/lib/shopify_app/configuration_test.rb

@jamesmacaulay @awd @ilikeorangutans 
Allow us to override the `myshopify_domain` from inside the `shopify_app.yml`. For internal use.
Bumps gem version to `5.0.2`.

Allow override myshopify_domain from shopify_app.yml

---

README.md
lib/generators/shopify_app/templates/config/initializers/shopify_session_repository.rb

when ShopifySessionRepository.storage = Shop is enabled in
config/initializers/shopify_session_repository.rb
and the Shop model is modified
it gives error :
ArgumentError (A copy of Shop has been removed from the module tree but is still active!)
in development.
to solve the error Shop is replaced with identifier self.
this solves the error in a simple manner
PS: I have never sent pull request. So, please merge to the branch you think suitable. (If mergeable)

Solves Error: A copy of Shop has been removed from the module tree but is still active!

---

lib/shopify_app/configuration.rb
lib/shopify_app/sessions_controller.rb
test/controllers/sessions_controller_test.rb
test/shopify_app/configuration_test.rb

This PR adds a configurable myshopify_domain to the ShopifyApp gem for internal use (and I suppose external use if an app dev has made a mock local shopify server).
@shawnfrench @stephenminded

add configurable myshopify_domain

---

lib/shopify_app/version.rb
shopify_app.gemspec

Now that 1.1.8 of omniauth-shopify-oauth2 is out we can bump the min version and remove the hard requirement on shopify_api 3.2.0.
@kevinhughes27 @clayton-shopify @Shopify/platform

Bump min version of omniauth-shopify-oauth2, remove hard requirement on shopify_api

---

lib/generators/shopify_app/shopify_app_generator.rb

closes #131 
This passes the arguments down into the install generator which uses them. Most users of this gem will probably use the simple `generate shopify_app` which does everything so it would be nice if cmd args worked here.
I wish passing args in between generators was cleaner but this works at least
for review:
@celsodantas @stephenminded

passes the options through to the install generator

---

lib/generators/shopify_app/install/templates/shopify_provider.rb
shopify_app.gemspec

@stephenminded & @kevinhughes27 for review
Require the latest version of omniauth-shopify-oauth2 gem and use the default setup lambda so that it doesn't need to be generated for each app.

Bump omniauth-shopify-oauth2 gem and use the default setup lambda.

---

lib/shopify_app/sessions_controller.rb
test/controllers/sessions_controller_test.rb

This PR adds the shopify shop name / domain to the session so its easier to see which shop the session is for. The main use for this is with exception catching tools that include the session with the exception. Currently all thats in the session is the id of the shop in the apps database which means you have to lookup which shop it actually is. With this addition you can see this right away.
for review
@shawnfrench @stephenminded

add shopify domain to session

---

README.md
app/controllers/authenticated_controller.rb
lib/generators/shopify_app/install/templates/home_controller.rb
lib/generators/shopify_app/install/templates/shopify_provider.rb
test/generators/controllers_generator_test.rb

I've noticed that its a pretty common error to refactor code into the ApplicationController and not realize that it affects the sessions controller. A pattern that I use a lot is to create an AuthenticatedController which has the required before filters for the authenticated part of the app. This helps prevent accidentally breaking auth for your app while refactoring into the ApplicationController.
I also pulled the layout config into AuthenticatedController and out of the generated HomeController. This is an improvement since now if you inherit AuthenticatedController everything just works
It seems a bit weird to me that then ApplicationController still gets ShopifyApp::Controller included since only its derived classes use these methods. The alternative would be to not include …

Authenticated controller

---

README.md

Adds a link to my App In Five screen cast under a new readme section called Quickstart. When I get around to doing the blog post I'll link it in the same section.
@joshubrown @atleeclark

add appinfive screencast to readme under Quickstart section

---

README.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/generators/shopify_app/install/templates/shopify_provider.rb
lib/shopify_app/configuration.rb
test/generators/install_generator_test.rb

since https://github.com/Shopify/shopify/pull/46095 redirect_uri is a required param for apps. This PR adds redirect_uri to the ShopifyApp config and the omniauth provider. It can be passed into the generators the same as api_key and other params.
@ShayneP and I top hatted a new app locally and were successful.
ToDo
for review @EiNSTeiN- @awd

add redirect uri to shopify app

---

lib/shopify_app/login_protection.rb
test/shopify_app/login_protection_test.rb

@kevinhughes27 @stephenminded I think this fixes the issue I found with `login_again_if_different_shop` not actually redirecting to the new shop.
There might be a better way to test this. Thoughts?

Close session in login_again_if_different_shop

---

lib/shopify_app/sessions_controller.rb

The `main_app.root_url` parameter is used to set the appropriate leading value for the path. This should fix issue #154 .

Use root_url from main_app when redirecting the user in authenticate

---

CHANGELOG
lib/shopify_app/login_protection.rb
lib/shopify_app/version.rb
test/shopify_app/login_protection_test.rb

`session[:return_to]` shouldn't be set if the request is an XHR, because browsing sessions rarely mean to be able to return to XHR paths.
Don't set it if the request is an XHR.
/related Shopify/facebook-commerce#3525
/review @kevinhughes27, @peterjm

Return an HTTP 401 for XHRs that aren't logged in

---

lib/generators/shopify_app/install/templates/shopify_provider.rb

Ensures that `ShopifyApp.configuration.redirect_uri` is actually used in oauth flow for apps using install generator.
Resolves issues #165 and #160

Add callback_url to shopify_provider.rb generator

---

lib/generators/shopify_app/shop_model/shop_model_generator.rb
lib/generators/shopify_app/shop_model/templates/shops.yml
test/generators/shop_model_generator_test.rb

While creating a new app with @christinejordan we realized that the shop model generator doesn't add any fixtures or even create the fixtures file. This PR adds that and it means one less thing for the user of this gem to do when setting up a new app.
for review:
@christinejordan @christhomson

create shop fixtures as part of shop model generator

---

lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/_flash_messages.html.erb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
test/generators/install_generator_test.rb

This PR adds the esdk flash messages template during app generation if the app is embedded. I also made the script smart enough to detect turoblinks and use the appropriate event (tophatted both locally). I don't think we should bother including anything flash related for non-embedded apps since there is a lot of different ways to do that and it would require some sort of default styling to actually work out of the box.
for review:
@christhomson @kwestein

include the flash messages partial in the embedded app generator

---

lib/generators/shopify_app/install/templates/shopify_app_ready_script.html

The filename for the favicon was wrong, so I updated it to use the correct favicon filename.
The default favicon file is empty, so I replaced it with a 1UP mushroom for testing purposes, which is displayed beside the app name:
@kevinhughes27 @shawnfrench

Updated the favicon file name in shopify_app_ready_script.html

---

CHANGELOG
README.md
lib/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/sessions_controller.rb
lib/shopify_app/webhooks_controller.rb
lib/shopify_app/webhooks_manager.rb
lib/shopify_app/webhooks_manager_job.rb
test/controllers/sessions_controller_test.rb
test/shopify_app/configuration_test.rb
test/shopify_app/webhooks_controller_test.rb
test/shopify_app/webhooks_manager_test.rb

This PR brings in the WebhooksManager that has made its way into most of our apps that require webhooks. It allows developers to say which webhooks their app needs in the ShopifyApp initializer and then the framework takes care of the rest. In the callback method when the shop is being installed or logged in we queue the webhooks manager to make sure all the required hooks are in place. This does require ActiveJob to be configured for the app to work properly since we wouldn't want to block waiting to talk to shopify again after the callback.
* This is totally optional and won't have any affect on existing apps unless they opt in and use this class
* If an app is using a background queue directly they can still use this. for example Sidekiq can live happily next to ActiveJob.
for review: …

add a webhooks manager to the framework

---

shopify_app.gemspec

@kevinhughes27 @EiNSTeiN- @christhomson
omniauth-shopify-oauth2 1.1.11 fixes an incompatibility with omniauth-oauth2 1.4.0 (https://github.com/Shopify/omniauth-shopify-oauth2/pull/32), so we should require that version.

Require omniauth-shopify-oauth2 ~> 1.1.11.

---

lib/generators/shopify_app/install/templates/shopify_provider.rb

thanks to #185 and the new omniauth gem we don't need to set the callback url any more.
@clayton-shopify @christhomson

remove callback url override since its been fixed upstream

---

app/views/sessions/new.html.erb

Breaking up #194 into smaller PRs. This one moves to more semantic/accessible markup for `sessions/new`.

more semantic/accessible markup for sessions/new view

---

lib/generators/shopify_app/install/templates/embedded_app.html.erb

Breaking up #194 into smaller PRs. This one moves to more performant/semantic/accessible markup for the embedded app view that’s consistent with what we’re doing in channels apps.

Markup for embedded app view

---

lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app_ready_script.html
lib/generators/shopify_app/install/templates/shopify_app_ready_script.html.erb

Breaking up #194 into smaller PRs. This one puts the `ready` JS into a `content_for :javascript` block. Depends on the `yield :javascript` in #198.

yield ready javascript

---

lib/generators/shopify_app/install/templates/_flash_messages.html.erb

Breaking up #194 into smaller PRs. Decided to leave the flash message stuff more or less alone since banners would require the assets gem. This PR just puts the flash JS into a content_for :javascript block.

yield flash message js

---

lib/generators/shopify_app/install/templates/index.html.erb

Breaking up #194 into smaller PRs. This one moves to more semantic/accessible markup for the products index.

more semantic/accessible markup for products index

---

CHANGELOG
README.md
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/shopify_app/version.rb

This PR updates some of the generated view markup and gets the output a little closer to how we use these apps. This is based on what we’re currently doing in channels, so forgive me if I'm making some faulty assumptions about what other apps might do.
Changes:
* more semantic/accessible markup
* remove the flash layout view, since we're no longer exposing errors in this way
* move render-blocking javascript to the bottom of the page to improve render time
* version bump, since some of this could be considered breaking changes (especially the flash message stuff)
closes https://github.com/Shopify/assets/issues/262

version bump after markup modernization

---

shopify_app.gemspec

fixes #211
I briefly looked into the other option of requiring activejob manually but its not quite as simple as I'd like and I think since most people will be using this gem with new applications that it is better to bump the minimum required version of rails.
I'll release a new version after this
for review @gmalette

bump rails version required

---

lib/shopify_app/login_protection.rb
test/shopify_app/login_protection_test.rb

I was having a problem with my application being redirected to a path with http instead of https. This allows the full url to be passed along with the secure protocol on this redirection.

Adds login_url to login_protection to allow https redirection properly

---

lib/generators/shopify_app/install/templates/embedded_app.html.erb

This include has been like this in our examples forever as far as I know but it recently started working (I did a bit of digging and it looks like chrome is getting more strict about mixed content now). This updates the generator to explicitly use https to grab the ESDK
@celsodantas @kmcphillips

use https for esdk include

---

lib/shopify_app/webhooks_controller.rb
test/shopify_app/webhooks_controller_test.rb

This PR updates `WebhookController` so we use ` ActiveSupport::SecurityUtils.secure_compare` to compare webhook data with the actual HMAC. This improves our ability to handle timing attacks.
@kevinhughes27 @djoume Please review.

Securely compare webhook hmac

---

README.md
lib/generators/shopify_app/shopify_app_generator.rb
test/generators/shopify_app_generator.rb

for the upcoming major version bump I am removing the controller, views and routes generator from the default all generator. Its unlikely that a developer needs to run these generators and it is preferred to let the engine own as much code as possible.
This is similar to how devise (probably the most popular engine) handles things.
I updated the readme to explain the process better.
@Krystosterone @gmalette

remove routes, views and controllers generators from the all generator

---

CHANGELOG
README.md
lib/generators/shopify_app/add_webhook/add_webhook_generator.rb
lib/generators/shopify_app/add_webhook/templates/webhook_job.rb
test/app_templates/config/initializers/shopify_app_with_webhooks.rb
test/generators/add_webhook_generator_test.rb
test/generators/routes_generator_test.rb
test/support/generator_test_helpers.rb

This PR adds a generator to accompany the new code for handling webhooks added in #217.
#217 added a fairly specific and Rails style way of handling webhooks and given the convention it added I think it makes sense to add a generator to add new webhooks to your app. Its a simple generator and the code can be added manually if the docs are read and understood.
The generator:
- Adds a new webhook to your ShopifyApp config
- Adds a new webhook_job using the delegation name convention and adds the jobs perform method
For review:
@Hammadk @nwtn @gavinballard

add add_webhook generator

---

CHANGELOG
README.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/generators/install_generator_test.rb

This PR cleans up the way the install generator receives arguments to use the code built into Rails. The install generator will also match the new add_webhook (#227) generator in terms of args now. I also cleaned up the tests and they are now easier to read and better test the generator since the args are passed in correctly.
This is sort of a breaking change since it affects how to use the generators but most users only do this once and we are already about to ship a major version.
@Hammadk @nwtn

update install generator to use rails generator arguments properly

---

CHANGELOG
QUICKSTART.md
README.md
example/config/initializers/omniauth.rb
example/config/initializers/shopify_app.rb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/generators/shopify_app/install/templates/shopify_provider.rb
lib/shopify_app/configuration.rb
test/generators/install_generator_test.rb

closes #203
The `redirect_uri` param was added in https://github.com/Shopify/shopify_app/pull/152 since Shopify required this param as of Shopify/shopify#46095. Omniauth was originally not sending this parameter correctly but it does now without us needing to set it (I didn't actually verify this addition but it does get sent now so I don't think finding the exact change in omniauth is required, also it might have been this Shopify/omniauth-shopify-oauth2/pull/32 that fixed it).
The inclusion of the `redirect_uri` parameter seemed to add to confusion for those mounting the engine at different locations (aka not `/`). I think not having it at all will be better since then anyone submounting will need to learn all the ins and outs of omniauth routing and won't be misslead by our parameter. …

remove the redirect uri param

---

README.md
lib/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/scripttags_manager.rb
lib/shopify_app/scripttags_manager_job.rb
lib/shopify_app/sessions_concern.rb
test/shopify_app/scripttags_manager_test.rb

resolves #209 
I've basically followed the same pattern of the WebhooksManager and WebhooksManagerJob to create a ScripttagsManager and ScripttagsManagerJob.
I've updated readme with instructions. I've tested this on my developing shopify app.

Adds ScripttagManager and job to auto create ScriptTag on shop creation

---

lib/shopify_app/login_protection.rb
test/controllers/sessions_controller_test.rb

@nwtn @kevinhughes27 I ran into the same issue as mentioned here https://github.com/Shopify/shopify_app/issues/230?_pjax=%23js-repo-pjax-container. 
We're making 2 authentication requests and (I think) the last one is beating the first one, causing the token to be invalid. There's some mention of it in this issue here https://github.com/intridea/omniauth-oauth2/issues/58#issuecomment-55061098. 
The error I get through Heroku logs is `Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`
I changed the refresh to 3 and had no issues, then changed it back to 0 and ran into the same issue. I then decreased from there and saw no issues with it at 1. 
I'm not certain this fixes the root cause, but it's seems to work. 
To replicate the …

Fixes CSRF OmniAuth issue

---

.travis.yml

As of February 24th, 2016;
> **About Ruby 2.0.0**
> As it has been announced before, all support for Ruby 2.0.0 has ended today. Bug and security fixes from more recent Ruby versions will no longer be backported to 2.0.0, and no further patch release of 2.0.0 will be released.
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
The current stable version is 2.3.0. While it introduces a lot of breaking changes (keyword arguments, frozen literals, the lonely operator, etc), I believe now is a good time to make the switch and avoid running on a deprecated version for too long. If you believe this is too much of a breaking change, I'd suggest to at least bump to 2.2.4. But I strongly believe a bump should happen.

Bump ruby version to 2.3.0

---

lib/shopify_app/scripttags_manager.rb
lib/shopify_app/scripttags_manager_job.rb
lib/shopify_app/webhooks_manager.rb
lib/shopify_app/webhooks_manager_job.rb
test/shopify_app/scripttags_manager_test.rb
test/shopify_app/webhooks_manager_test.rb

Here's the solution we discussed earlier. All managers would now be session agnostic, which gives to the caller the responsibility to instantiate it. With that being done, we'll be able to expose methods such as `create_webhook` and `create_scriptag` as independent methods, without the fear to interfere with an already existing session.  
@kevinhughes27 @alanhill

Managers are now shopify session agnostic

---

CHANGELOG
lib/shopify_app/version.rb
shopify_app.gemspec

This PR closes https://github.com/Shopify/shopify_app/issues/251 by updating the required Rails version to `4.2.6`. 
@kevinhughes27 Please review.

Bump gemspec to require rails 4.2.6+

---

CHANGELOG
lib/shopify_app/version.rb
shopify_app.gemspec

Bump dependency on shopify_api to 4.2.x. The current version 4.0.2 will be a year old tomorrow...
@kevinhughes27 @christianblais

Depend on shopify_api 4.2.x

---

lib/generators/shopify_app/shop_model/shop_model_generator.rb
lib/generators/shopify_app/shop_model/templates/db/migrate/create_shops.rb
lib/generators/shopify_app/shop_model/templates/shop_helper.rb
test/app_templates/app/controllers/shopify_app/authenticated_controller.rb
test/generators/shop_model_generator_test.rb
test/support/generator_test_helpers.rb

In all the apps I've been creating, in all apps I've seen on Shopify, and I'm pretty sure in all apps relying on the Shop model for memory store, we always need to retrieve the shop model at one point or another, from the database. Since this is a snippet of code we've been copying over and over again, I figure it could make sense to have it as part of the generator?
The output would be appended to `application_controller.rb`, allowing any other controller to rely on the `shop` helper.
What do you think? Worth it or not?
@kevinhughes27

Create shop helper with shop model generation

---

app/controllers/shopify_app/webhooks_controller.rb

This PR adds basic support to rails 5 in webhooks controller. The problem is that `ActionController::Parameters` cannot be serialized, and they're empty if not whitelisted using `permit!`. 
I don't know how to test this without a series of potentially breaking PRs in `shopify_api`
@sgnr @kevinhughes27

Support rails 5 in webhooks controller

---

app/controllers/shopify_app/authenticated_controller.rb

Rails 5 deprecated all `_filter` callbacks in favour of `_action`.
@kevinhughes27

Use around_action and fix deprecation warnings

---

lib/shopify_app/login_protection.rb
test/shopify_app/login_protection_test.rb

This fixes #245 by ensuring that the shop params are passed when the app is uninstalled, but session persists.
[Screencast here](https://screenshot.click/24-12-1dekx-sljz3.mp4)
@kevinhughes27, @jamiemtdwyer for 👀

prevents shop params from being dropped on second installation attempt

---

.travis.yml
Gemfile.rails50
lib/shopify_app/app_proxy_verification.rb
lib/shopify_app/webhook_verification.rb
shopify_app.gemspec
test/controllers/sessions_controller_test.rb

Ref: https://github.com/Shopify/shopify_app/pull/288
Adds a Gemfile to ensure we're testing against Rails `~> 5.0`. Even though it's the latest version, this gem will still resolve to Rails `4.2.6` by default.
This also adds Ruby `2.3.1` to be tested in Travis.
/cc @kevinhughes27

Travis CI - test multiple Rails versions

---

CHANGELOG
lib/shopify_app/scripttags_manager.rb
lib/shopify_app/scripttags_manager_job.rb
lib/shopify_app/sessions_concern.rb
lib/shopify_app/webhooks_manager.rb
lib/shopify_app/webhooks_manager_job.rb
test/shopify_app/scripttags_manager_test.rb
test/shopify_app/webhooks_manager_test.rb

Currently our resource managers read the configuration from ShopifyApp directly to determine what they need to do which works fine in environments where this config is static (this covers probably 95% of use cases). We have some applications that host multiple Shopify Apps where this is not the case and blocks us from using the managers (One use case for multiple apps is integrations where each integration warrants a spot in the app store and a separate experience for the user but a lot of code can be shared on the backend eg. accounting export).
The solution to this problem is to pass the configuration into the manager before creating the resources. This way if the ShopifyApp config is changed by the controller the most up to date information is used by the manager. As a bonus its also …

Pass Config to Webhook and Scripttag Managers

---

README.md

Closes #287 
Adds the rails 5 installation note from `shopify_api`. 
https://github.com/Shopify/shopify_api#rails-5
@kevinhughes27

Add installation note about rails 5

---

.travis.yml
Gemfile.ruby22
Gemfile.ruby22.rails50
shopify_app.gemspec

Allows `shopify_api` versions above 4.2 while disallowing < 4.2.2, fixing the regression in 13d92a8415b1f08d260a529b762077b04f3dd619

soften shopify_api dependency

---

CHANGELOG
app/controllers/shopify_app/authenticated_controller.rb
example/app/controllers/application_controller.rb
lib/generators/shopify_app/install/install_generator.rb
lib/shopify_app/sessions_concern.rb
test/generators/install_generator_test.rb

I recently made this change in some of my apps and think it belongs up stream. With this change ShopifyApp only modifies controllers it owns and it doesn't make anything any harder for the developer.
SessionsController and AuthenticatedController (both in the ShopifyApp namespace) require the module and therefore include it. Other controllers that inherit from ApplicationController don't have to worry about any name clash or added behaviour.
I ran an install flow 🎩  locally
For review:
@SebastianSzturo @alexcoco

only include login protection where required

---

CHANGELOG
README.md
lib/generators/shopify_app/app_proxy_controller/app_proxy_controller_generator.rb
lib/generators/shopify_app/app_proxy_controller/templates/app_proxy_controller.rb
lib/generators/shopify_app/app_proxy_controller/templates/app_proxy_route.rb
lib/generators/shopify_app/app_proxy_controller/templates/index.html.erb
lib/shopify_app/version.rb
test/generators/app_proxy_controller_generator_test.rb

This branch deals with the addition of an optional App Proxy Controller Generator that is based on existing generators within shopify_app.
It creates:
- The AppProxyController which inherits from ApplicationController and conditionally includes the AppProxyVerification mixin alongwith sending "Content-Type='application/liquid'" header for only production environment.
- The associated view for index action that displays current shop info.
Additionally it injects the namespace route for the controller as currently defined into the routes.rb.

App Proxy Generator

---

CHANGELOG.md
README.md
app/views/shopify_app/sessions/new.html.erb
example/config/initializers/shopify_app.rb
lib/shopify_app/configuration.rb

@kevinhughes27 /cc @christianblais 
This adds a new configuration field called `application_name`. This name will be used (if present) on the login page instead of "Shopify App – Installation". I've also updated the copy on the login page.

Add application_name config and update sessions#new view copy

---

lib/shopify_app/app_proxy_verification.rb
lib/shopify_app/webhook_verification.rb
test/shopify_app/app_proxy_verification_test.rb
test/shopify_app/webhook_verification_test.rb

Fixes a regression caused in 653942f which added `raise: false` for Rails 5 compatibility.
This does end up affecting Rails 4 apps as well so now we're explicitly handling this based on Rails version.
Another issue was that the tests weren't raising this error so the regression wasn't found. This also fixes the controller tests to ensure they will raise errors in the future.
@kevinhughes27

Fix #304 - Handle skip_before_action based on Rails version

---

README.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/app_templates/config/initializers/shopify_app.rb
test/generators/install_generator_test.rb

Add new application_name option to the app generator

---

index.md
quickstart.md

Currently, the link to Quickstart follows the page on the master branch instead of gh-pages.
This PR changes that and additionally syncs the index page to README on master

Add QUICKSTART to gh-pages

---

.travis.yml
shopify_app.gemspec

2.2.4 was a bit arbitrary and this matches up with Rails 5.0 better which also requires >= 2.2.2
We could tag this as 7.1.1
@kevinhughes27 
/cc @sshaw

Require Ruby 2.2.2 instead of 2.2.4

---

example/app/views/layouts/_flash_messages.html.erb

For this generated example, we can use `#escape_javascript` instead of `#j`, as it's more obvious what the former does.
/review @kevinhughes27 @alexcoco please

Use more obvious method name

---

CHANGELOG.md
app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/sessions_concern.rb
lib/shopify_app/version.rb

The SessionsController inherits rendering using the application layout.
By default, render with no layout at all.
/review @kevinhughes27 @alexcoco @swalkinshaw
/cc @nickhoffman

Bypass application layout rendering for SessionsController

---

README.md
TROUBLESHOOTING.md

When using the shopify_app gem naively, but according to documentation, the session in the app's session store will not be deleted when the app is uninstalled.
That leads to a situation where a re-installation of the app is not possible because the app still has an outdated session.
You can use the app/uninstalled hook though to delete the session and fix this problem. This PR documents that.

add troubleshooting hint about reinstallation problems when session isn't deleted

---

README.md

Without specifying protocol (http/https) the webhook won't be created, and ShopifyAPI::Webhook will return an error

 Update to correct url in webhook example

---

lib/shopify_app/webhook_verification.rb

`variable_size_secure_compare` exists to protect against timing attacks that could reveal the length of the inputs. Since the inputs are SHA256 hmacs, their length is already known and nothing is gained from using `variable_size_secure_compare`. Switching to `secure_compare`, which short circuits if the inputs' lengths are not the equal.

Use fixed-size `secure_compare` in `WebhookVerification#hmac_valid?`

---

CHANGELOG.md
README.md
lib/shopify_app/scripttags_manager.rb
lib/shopify_app/scripttags_manager_job.rb
test/shopify_app/scripttags_manager_job_test.rb
test/shopify_app/scripttags_manager_test.rb

Should probably add a test to make sure src returned by `#call` is not cached in the global list. 
Somewhat related question: under what circumstances [does this get called](https://github.com/Shopify/shopify_app/blob/076a2966823cfa2d74179cda675ff942de707c7a/lib/shopify_app/scripttags_manager.rb#L49) as if the API cannot create a resource an exception is raised.

Dynamic scripttags

---

CHANGELOG.md
README.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/generators/install_generator_test.rb

Patch install_generator to allow whitespace

---

lib/shopify_app/webhooks_manager.rb
test/shopify_app/webhooks_manager_test.rb

sometimes the shopify api can return a nil to us. so lets make sure we dont try to call #each on nil.
@kevinhughes27

Handle empty webhook result sets

---

CHANGELOG.md
lib/shopify_app/login_protection.rb
lib/shopify_app/sessions_concern.rb
lib/shopify_app/version.rb
test/controllers/sessions_controller_test.rb
test/shopify_app/login_protection_test.rb

A recent change was proposed in [Chrome Canary 57.0.2933.0](https://github.com/WICG/interventions/issues/16) that will break embedded app authentication. 
* Instead of using `window.location.origin` to redirect to the authentication URL, we should use ` window.parent.postMessage` (this logic is in `#fullpage_redirect_to`).
This PR won't be merged until extensively tested
Related refactor:
* This PR also replaces `#redirect_to_with_fallback` with the Rails method: `redirect_to`. `#redirect_to_with_fallback` doesn't work like we think it does. The status and location headers take priority over the inline response. The fallback only happens if the browser ignores the status and location headers -- which doesn't happen on any modern browser.
* This PR moves `#sanitized_shop_name` and …

Use postMessage to redirect to Shopify during authentication

---

CHANGELOG.md

Since versions `7.2.1` and `7.2.2` were not released, think its better to group `CHANGELOG` entries for those versions under the latest release.
--
/cc @Hammadk , @kevinhughes27

bundle unreleased entries into latest release

---

CHANGELOG.md
lib/shopify_app/sessions_concern.rb
test/controllers/sessions_controller_test.rb

This changes sessions#new to check if the shop parameter received is valid before calling authenticate. Currently we just check if `params[:shop].present?`, but this causes some strange redirect behaviour on unexpected shop values. 
If we call an app with an invalid shop value (ex. `shop=example.com`), it will pass that to authenticate. Since `sanitized_shop_name.present?` would be false in this case, it redirects to `return_address`. If the `return_address` calls sessions#new again, this results in circular redirects.
@kevinhughes27 @gauravmc

Sanitizes the shop param to only call authenticate on valid input

---

lib/shopify_app/login_protection.rb
test/controllers/sessions_controller_test.rb

The current [`ShopifyApp::LoginProtection.redirection_javascript`](https://github.com/Shopify/shopify_app/blob/e38a0e2892269f804a3768a3dc9181d34ec3eb48/lib/shopify_app/login_protection.rb#L82-L86) only allows you to pass in a relative URL (`/login`). This is because we always set the location in `#postMessage` to:
``` javascript
data: { location: window.location.origin + #{url.to_json} }
```
Instead, we need to allow absolute URLs as well (`https//SHOP.myshopify.com/admin/charges`). We create a normalized link to do this:
``` javascript
normalizedLink = document.createElement('a');
normalizedLink.href = #{url.to_json};
data: { location: normalizedLink.href }
```
Tested in the following browsers:
Fixes https://github.com/Shopify/shopify_app/issues/387

Allow absolute URLs in ShopifyApp::LoginProtection.redirection_javascript

---

lib/shopify_app/login_protection.rb
test/controllers/sessions_controller_test.rb
test/generators/home_controller_generator_test.rb
test/shopify_app/login_protection_test.rb

In https://github.com/Shopify/shopify_app/issues/398 we found that `fullpage_redirect_to` cannot be used when the `:shop` param is not present and the shop is already logged in. This PR solves this problem by grabbing the domain from the session.
At this point I am not sure if there is a better method of grabbing the domain. Another option is to`ShopifyApp::SessionRepository.retrieve(session[:shopify]).shopify_domain`
Sidenote: Our setup for `LoginProtectionTests` is pretty weird. I'd like to unit test `fullpage_redirect_to` but that's not straight forward.

Update LoginProtection#fullpage_redirect_to to get shopify domain from session

---

CHANGELOG.md
lib/shopify_app/version.rb

This PR updates just packages this gem for a [minor version bump](https://github.com/Shopify/shopify_app/blob/master/RELEASING). Closes https://github.com/Shopify/shopify_app/issues/398

Package for release 7.2.6

---

test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/shopify_app/configuration_test.rb
test/shopify_app/utils_test.rb

This PR fixes a flakey test that fails when another test sets `ShopifyApp.configuration.myshopify_domain = myshopify.io`. I am rushing this PR so we can get 7.2.6 out the door. I'll follow up and help refactor these tests.

Use .com domains in tests, fix flakey test

---

example/config/initializers/shopify_session_repository.rb
lib/generators/shopify_app/shop_model/templates/shopify_session_repository.rb

When Rails 5.1 comes out, the use of `ActionDispatch::Reloader#to_prepare` here will cause the session initializer to break.
This fixes the following deprecation warning, while maintaining support for Rails 4 and below:
> DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead)

Rails 5: ActionDispatch::Reloader#to_prepare is deprecated

---

.travis.yml
Gemfile.rails40
Gemfile.rails50
README.md
lib/shopify_app/app_proxy_verification.rb
lib/shopify_app/webhook_verification.rb
shopify_app.gemspec
test/controllers/sessions_controller_test.rb
test/integration/webhooks_controller_test.rb
test/shopify_app/app_proxy_verification_test.rb
test/shopify_app/localization_test.rb
test/shopify_app/login_protection_test.rb
test/shopify_app/webhook_verification_test.rb
test/shopify_app/webhooks_manager_test.rb

We need to remove support for Rails 4 because changes to the testing syntax In Rails 5 are not compatible with this version.
This PR makes the following changes:
* Update Travis CI to only test Rails 5
* Update test syntax to match Rails 5
* Clean up tests

Remove support for rails 4

---

CHANGELOG.md
lib/generators/shopify_app/shop_model/shop_model_generator.rb
lib/generators/shopify_app/shop_model/templates/db/migrate/create_shops.erb
lib/shopify_app/version.rb

Closes https://github.com/Shopify/shopify_app/issues/415
Rails 5 requires the Rails version in the migration parent class apparently. This PR adds that via an erb template. It has to be in a minor version format `[x.x]`
Do I need to bump a version number somewhere?

Added Rails version to create_shops generator template

---

config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/ja.yml
lib/shopify_app/sessions_concern.rb
test/controllers/sessions_controller_test.rb

This PR removes the `Logged in` message. Please see this issue for reference: https://github.com/Shopify/shopify_app/issues/424

Remove 'Logged in' flash message

---

test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/generators/home_controller_generator_test.rb
test/shopify_app/configuration_test.rb
test/shopify_app/login_protection_test.rb
test/shopify_app/utils_test.rb
test/test_helper.rb

Tests have to reset the default `ShopifyApp.configuration` to prevent leaky tests. This means that more context is required when writing tests, and more boilerplate code.
Set the default configuration with `ShopifyAppConfigurer.call` before each test.

Improve tests: reset ShopifyApp configuration before each test

---

lib/shopify_app/login_protection.rb

`LoginProtection#login_again_if_different_shop` is a before action that forces re-login is another shop is already logged in. Currently it only works when `params[:shop].is_a?(String)`. As far as I can tell, there is no good reason to keep that around.

Minor change: Expect params[:shop] to be a string

---

CHANGELOG.md
app/controllers/shopify_app/authenticated_controller.rb
app/controllers/shopify_app/sessions_controller.rb
app/controllers/shopify_app/webhooks_controller.rb

I'm working on mounting ShopifyApp in an application where most of the code is not part of the Shopify application. One of things I came across is that our ApplicationController defines a few before_actions which interfere with the engine. I think this change makes sense since we wouldn't want ApplicationController to interfere with anything inside the engine.
review
@Hammadk @alanhill

subclass from ActionController::Base not Application controller

---

CHANGELOG.md
README.md
lib/generators/shopify_app/add_after_authenticate_job/add_after_authenticate_job_generator.rb
lib/generators/shopify_app/add_after_authenticate_job/templates/after_authenticate_job.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/sessions_concern.rb
lib/shopify_app/version.rb
test/controllers/sessions_controller_test.rb
test/generators/add_after_authenticate_job_generator_test.rb
test/generators/install_generator_test.rb
test/shopify_app/configuration_test.rb

Adds the ability to generate an after authenticate job which can perform async or inline once the shop has authenticated with the app.
Branch renamed from: https://github.com/Shopify/shopify_app/pull/428 to better reflect the changes. 
@Hammadk @kevinhughes27 ready for review again - made the config a hash accepting `job` and `inline`.

Add after authenticate job option

---

CHANGELOG.md
app/controllers/shopify_app/authenticated_controller.rb
lib/generators/shopify_app/install/install_generator.rb
lib/shopify_app.rb
lib/shopify_app/controller_concerns/embedded_app.rb
lib/shopify_app/controller_concerns/localization.rb
test/generators/install_generator_test.rb

One thing I didn't like when I went to use this engine on a project where the embedded app is a small thing compared to the whole app was how we still configured headers for the ESDK globally. I looked into how to avoid this because I didn't want to add these headers for my whole application. I found it was pretty easy to do locally in newer versions of rails (this may have been hard in the past I am not sure).
I also updated the Localization concern to fully abstract itself while I was nearby.
@swalkinshaw @Hammadk

EmbeddedApp Concern

---

CHANGELOG.md
lib/generators/shopify_app/home_controller/templates/home_controller.rb
lib/generators/shopify_app/home_controller/templates/index.html.erb

This PR adds Webhooks to the generated HomeController. This is useful since it shows users how to view the webhooks per shop. Its pretty common for people to get confused and check the webhooks list in the admin which only shows the Shop's webhooks not the App's. I am hoping this change will help alleviate this confusion.
New generated home view:
@jamiemtdwyer @alanhill

add webhooks to example home controller

---

CHANGELOG.md
README.md
app/controllers/shopify_app/webhooks_controller.rb
lib/shopify_app/configuration.rb
test/shopify_app/configuration_test.rb

This tweak allow specifying a namespace for the webhook jobs.
Rationale: I'm trying to build a generic ecommerce app, keeping in mind that I may expand to support non-Shopify stores in the future. With that in mind, I've namespaced my ShopifyApp webhook jobs under `jobs/shopify/xxx_job.rb`, but despite mounting ShopifyApp under '/shopify', the webhook controller was always raising ShopifyApp::MissingWebhookJobError because it was hardcoded to assume the webhook job names were in the top-level namespace.

Allow specifying namespace for webhooks jobs

---

lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Reverts Shopify/shopify_app#430, and adds a test to prevent regression.
In Shopify/shopify_app#430, I removed the `params[:shop].is_a?(String)` check from `LoginProtection:: login_again_if_different_shop` because we didn't think it was needed.
While working on another project I found out that this check is needed. Consider the case where someone has a `Shop` model in Rails. When they use form_for in a controller, Rails passes along the params under the `shop` hash, so:
``` ruby
shop : {
id: 123,
foo: bar
}
```
If this hash is passed to `login_again_if_different_shop`, the following check is always true: `shop_session.url != params[:shop]`. Of course, using the non-default param gets around this.

Ignore non-String shop params in login_again_if_different_shop

---

CHANGELOG.md
lib/shopify_app/controller_concerns/embedded_app.rb

fixes #468
@resistorsoftware / @meulmees lets try this fix suggested [here](https://stackoverflow.com/questions/18445782/how-to-override-x-frame-options-for-a-controller-or-action-in-rails-4)

change how the X-Frame-Options header is removed

---

lib/generators/shopify_app/install/templates/_flash_messages.html.erb

Update event name to trigger the handler on newer Turbolinks versions. Explicitly remove the event listener after the flash notice (or error) is triggered once.

Make compatible with Turbolinks >= 5.0.0

---

CHANGELOG.md
lib/shopify_app/controller_concerns/app_proxy_verification.rb
test/shopify_app/controller_concerns/app_proxy_verification_test.rb

when app proxy verification fails, send 403 instead of 401

---

app/controllers/shopify_app/authenticated_controller.rb

In release 8.0.0 on Aug 14th, CSRF protection was removed from `ShopifyApp::AuthenticatedController`, this PR adds it back.
Once this merges, I'll bump the gem version + update README with the preferred version in a note, and title the PR something eye-catching so that our watchers will know to update.
@kevinhughes27 @yaworsk

Add CSRF Protection on AuthenticatedController

---

app/controllers/shopify_app/sessions_controller.rb

This prevents a browser error where the login route is called from the embedded app iframe.

Remove X-Frame-Options header on login route

---

app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/new.html.erb
config/locales/en.yml
config/locales/fr.yml
test/controllers/sessions_controller_test.rb

Right now when an invalid url is entered (one that is from an invalid host) nothing is displayed to the user to let them know something is wrong. This PR adds a simple error message
(only .com is supported by default)

Show an error message when entering an invalid url

---

lib/generators/shopify_app/install/install_generator.rb

The `install` generator doesn't do anything involving ActiveRecord, so this `require` is unnecessary here

don't require 'rails/generators/active_record' in install generator

---

app/views/shopify_app/sessions/new.html.erb

On #513, the login form method was changed from GET to POST. This causes Rails to raise an invalid token error. Using the form_tag helper, the form automatically gets a hidden input with the token, to protect from CSRF attacks.

Use form_tag helper to create login form

---

app/views/shopify_app/sessions/new.html.erb

The https://github.com/Shopify/better-html gem raises errors when serving this file because `error` is unquoted.

Add missing quotes around error class in sessions/new

---

.rubocop.yml
lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/sessions_controller_test.rb
test/shopify_app/controller_concerns/login_protection_test.rb

https://github.com/Shopify/shopify_app/pull/459 introduced shopify_user in session, and it's cleared out here: https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/sessions_controller.rb#L32
However, we should clear it out as well in login_protection

clear shopify_user in session

---

example/bin/spring

Gem.path does not take parameters.  Fixing to be compliant with latest changes

Update spring to be compatible with changes

---

example/app/views/layouts/_flash_messages.html.erb
lib/generators/shopify_app/install/templates/_flash_messages.html.erb

The flash messages generated by this app just caused a PR I created that makes use of the `shopify_app` gem to get flagged for review.
See https://github.com/Shopify/payment_gateway_sample_app/pull/1
Just updating the cause at the source.

Update javascript flash message from html_safe

---

.gitignore
lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

I needed to do a full page redirect and so I used the one from `LoginProtection` since I'm including that concern in my controller. I noticed the redirect was failing due to some missing instance variables. I realized that `ShopifyApp::LoginProtection`, together with `ShopifyApp::EmbeddedApp` renders the embedded_app layout file and then yields redirect HTML+JS.
`ShopifyApp::AuthenticatedController` mixes in both `ShopifyApp::LoginProtection` and `ShopifyApp::EmbeddedApp`:
```ruby
module ShopifyApp
class AuthenticatedController < ActionController::Base
include ShopifyApp::LoginProtection
include ShopifyApp::EmbeddedApp
end
end
```
So, I'd assume that in most cases the rendered redirection page looks like this:
```html
<!DOCTYPE html>
<html lang="en">
<body>
<div class="app-wrapper">
<div …
```

Skip layout when doing full page redirect

---

README.md

- http://api.shopify.com does not give me anything to read. The "Read the docs" link covers the API anyway. So remove the link to api.shopify.com
- Use current URLs
- Prettify

Fix outdated "Questions or probems" links in readme

---

translation.yml

**Owners:** 
This PR contains the configuration files required to have your source (English) strings sent for translation, and receive translations back into your repository.
- `buyer` for end users of Shopify stores
- `merchant` where the users are merchants
- `partner` for Shopify partners
Questions about this PR? Hop in the `#intl-services` Slack channel. We're happy to help!
@Shopify/translation-platform

Add initial configuration for translation platform

---

README.md
lib/shopify_app/configuration.rb
test/shopify_app/controller_concerns/login_protection_test.rb

While working on our embedded app we ran into a requirement where we want to redirect users to a separate landing page in order to go through the login flow.
Currently the `shopify_app` gem redirects to `login_url` but that's hard coded to be essentially `"#{root_url}/login"`
This PR adds a `login_url` `attr_accessor` so that clients can configure the login URL. It defaults to the old behaviour until you've customized the URL.
ex:
```ruby
ShopifyApp.configure do |config|
config.login_url = 'https://my.domain.com/some/route/login
end
```

Adds the ability to configure the login_url

---

README.md
example/config/initializers/shopify_app.rb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/generators/install_generator_test.rb

With reference to: [Issue](https://github.com/Shopify/shopify/issues/166090)

Removing the read_orders scope from list of default scopes provided to a generated app

---

README.md
example/config/initializers/shopify_app.rb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/generators/install_generator_test.rb

Reverts Shopify/shopify_app#629

Revert "Removing the read_orders scope from list of default scopes provided to a generated app"

---

lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

There's no reason why we should error on an uppercase shop domain since they are technically valid.
Closes #622

Downcase shop domains on login

---

example/config/initializers/omniauth.rb
example/db/schema.rb
shopify_app.gemspec

In investigating some reports of the example app in this repo not working correctly I discovered that `shopify_auth_params` here is `nil`. After a bit of a goose chase I [fixed the inconsistency](https://github.com/Shopify/omniauth-shopify-oauth2/pull/71) between pulling `shop` from session/param in the omniauth library.
Now developers can use this gem without having to set a custom `setup` key in the initializer so I'm removing it from the examples.
Reports:
#354 
#598
https://github.com/Shopify/shopify_app/issues/467#issuecomment-402637019
https://github.com/Shopify/omniauth-shopify-oauth2/issues/61
https://github.com/Shopify/omniauth-shopify-oauth2/issues/64
Copy some API keys into a `.env` file in the `example/` directory.
```
cd example/
bundle install && bundle exec rake db:migrate …
```

Clean up omniauth setup

---

README.md

It seems to me like the `true` and `false` should change place in order for the sentence makes sense.
After this change the sentence will read:
>If you need to load your app outside of the Shopify admin -- you can change `forceRedirect: true` to `false`

Fix instructions for preventing forceRedirect

---

README.md

Update the wording of the `Tunnelling` section of the README to:
- emphasize the requirements for local tunnelling
- show an example of using ngrok
- update the instructions for setting up app urls to match the field names in the Partners Dashboard
Closes #680

Update README to clarify tunneling/embedding

---

app/assets/javascripts/shopify_app/storage_access.js
shopify_app.gemspec

Fixes #677.
I’m not that familiar with our ITP solution, so I’m looking for feedback on the direction here.
We already have a check on the number of install redirects; this try/catch block just makes sure that this is the path we go down if users have explicitly turned off third-party cookies.

Fix infinite loop when third-party cookies are disabled

---

shipit.rubygems.yml

Policial is doing weird things (trying to analyze the wrong PR) and blocking deploys in Shipit. We don’t want Policial affecting Shipit.

Hide policial from shipit

---

app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

If an individual logs into `Shop1` as `User1` and installs an app on `Shop1` both a `session[:shopify]` and `session[:shopify_user]` are created.
If the individual then logs into `Shop2` as `User2` and installs the same app `session[:shopify]` will now properly refer to `shop2.myshopify.com` but the `session[:shopify_user]` will still refer to `User1`.
If no `associated_user` is present in the callback we should clear the stale `session[:shopify_user]` since it isn't relevant anymore.

Clear stale shopify_user sessions

---

translation.yml

We are now translating Shopify into [nl](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=nl), [zh-CN](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=zh), [zh-TW](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=zh).
Unless you have a specific reason not to, simply merge this mandatory change to your `translation.yml` file.
For any questions, contact [#intl-services](https://shopify.slack.com/messages/C7TJQLVC7/).
**Owners:** @Shopify/platform-dev-tools-education

Update configuration languages in translations.yml

---

.gitignore
.rubocop.yml
README.md
lib/generators/shopify_app/add_after_authenticate_job/add_after_authenticate_job_generator.rb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/generators/shopify_app/install/templates/shopify_provider.rb
lib/generators/shopify_app/rotate_shopify_token_job/rotate_shopify_token_job_generator.rb
lib/generators/shopify_app/rotate_shopify_token_job/templates/rotate_shopify_token.rake
lib/generators/shopify_app/rotate_shopify_token_job/templates/rotate_shopify_token_job.rb
lib/shopify_app/configuration.rb
lib/shopify_app/controller_concerns/webhook_verification.rb
shopify_app.gemspec
test/generators/install_generator_test.rb
test/generators/rotate_shopify_token_job_generator_test.rb
test/shopify_app/controller_concerns/webhook_verification_test.rb

Relates to https://github.com/Shopify/buy-button/issues/2739
- Extend the hmac validation to support both previous and new token when a secret rotation is happening. 
- Add a job generator, to make requests to all `shops` to update their `shopify_token` with the use of a `refresh_token`. This should work for any consumer that has `shopify_token` and `shopify_domain` in their `shops` table.
PR by @jamiemtdwyer and @jmignac

Abstract support to secrets rotation

---

app/assets/javascripts/shopify_app/storage_access.js

@nwtn, @sergey-alekseev
Another fix on top of #684. I only now had the chance to test how 8.4.2 works on MS Edge (v44), when third-party cookies are blocked, and it still results in an infinite loop. 
Edge does't throw an error when we try to set session storage or cookies, even if third-party cookies are blocked. My solution is to manually check and throw the error if cookies are empty, after we just attempted to set one.

Fix infinite loop when Edge has third-party cookies blocked.

---

example/config/initializers/session_store.rb

See https://github.com/Shopify/merchant-experience-of-apps/issues/196
In order to optimize performance of apps on mobile, subsequent load time can be reduced if the app uses persisted cookies. This updates the example to include this suggestion.

Add expiry to cookies to allow persisted cookies in example

---

example/Gemfile
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/session_store.rb

Addresses https://github.com/Shopify/shopify_app/pull/703#issuecomment-471657509
This includes a template for the generator that configures the `session_store` to include a persisted cookie.

Include session_store template in the install generator

---

test/shopify_app/configuration_test.rb

Recently I observed these test failures: https://travis-ci.org/Shopify/shopify_app/jobs/509660290
The failures can be reproduced locally with `SEED=6112 bundle exec rake test`.
They occur because a test modifies the `root_url` configuration option and fails to reset it at the end of the test.

Restore the original root_url to fix a leaky test.

---

CHANGELOG.md
README.md
app/controllers/concerns/shopify_app/authenticated.rb
app/controllers/shopify_app/authenticated_controller.rb
example/app/controllers/authenticated_controller.rb
example/app/controllers/home_controller.rb
lib/generators/shopify_app/authenticated_controller/authenticated_controller_generator.rb
lib/generators/shopify_app/authenticated_controller/templates/authenticated_controller.rb
lib/generators/shopify_app/home_controller/templates/home_controller.rb
lib/generators/shopify_app/shopify_app_generator.rb
lib/shopify_app/version.rb
test/controllers/concerns/authenticated_test.rb

Currently, any app that uses `shopify_app` needs to inherit from `ShopifyApp::AuthenticatedController` so those parts of their app receive Shopify authentication. This has the unfortunate consequence that controllers cannot inherit from the application's actually `ApplicationController` and leads to a situation where there's no place for shared functionality of both authenticated and unauthenticated controllers can go.
This PR adds a `Authenticated` concern, which can simply be included in an `AuthenticatedController` defined by the app, which can then inherit from `ApplicationController` and benefit from any shared functionality therein.

Add a concern ShopifyApp::Authenticated so apps don't have to inherit from AuthenticatedController

---

shopify_app.gemspec

Next major version of shopify_api will have breaking changes and will require a new version for shopify_app.  
This change stops `8.6.x` to  not bump up to the 7.0 version for shopify_api

Set highest gem version for shopify_api.

---

lib/shopify_app/session/session_storage.rb

Following an upgrade to rails 6.0.0beta3 I've received a lot of warning concerning the uniqueness of the `shopify_domain` and the fact that rails 6.1 will no longer enforce case sensitive comparison by default.
More informations at https://github.com/rails/rails/blob/master/guides/source/active_record_validations.md#uniqueness
Let's mark the uniqueness as non-case-sensitive by default cause `MyShop.myshopify.com` should be equal to `myshop.myshopify.com` anyway.
This would limit the noise when running tests on an app that is using `Shopify_app`
Example:
```bash
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :shopify_domain attribute in Shop model, pass `case_sensitive: true` option …
```

Make uniqueness case insensive by default.

---

shipit.rubygems.yml

Ship-it documentation points that the hide needs to be under the `ci:` configuration space.  
https://github.com/Shopify/shipit-engine#ci

Move policial under the ci hide to ignore for release.

---

README.md

This link was a 404, now it is not.
https://github.com/Shopify/shopify_api/blob/master/README.md#-breaking-change-notice-for-version-700-

Fix link to README

---

lib/shopify_app/managers/webhooks_manager.rb
test/shopify_app/managers/webhooks_manager_test.rb

Described in #700, it is possible for `.all` on an ActiveResource object to return `nil` and not just an empty array.
This causes the `WebhooksManager` to raise calling `nil#index_by` in this case. 
Coerce `nil.to_a` to force `[]`. It's done a few lines above in the same file in the same way.

Handle Webhook.all raturning `nil` and raising on `index_by`

---

shopify_app.gemspec
test/controllers/sessions_controller_test.rb

Otherwise we incorrectly detect Shopify Mobile, which displays the ITP screen unnecessarily.
See: https://github.com/Shopify/shopify_app/issues/734

Force newer version of browser_sniffer

---

package-lock.json
yarn.lock

We had both a `yarn.lock` file and an npm `package-lock.json` file, neither of which were up-to-date or in sync. This removes the yarn file and updates `package-lock.json` to fix a security issue.

update node_module lock files

---

README.md

“WebhookVerification” was missing an “i”

correct typo in readme

---

example/app/assets/javascripts/flash_messages.js
example/app/assets/javascripts/shopify_app.js
example/app/views/layouts/_flash_messages.html.erb
example/app/views/layouts/embedded_app.html.erb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/_flash_messages.html.erb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/flash_messages.js
lib/generators/shopify_app/install/templates/shopify_app.js

[Content Security Policy(CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) is an additional layer of security that helps detecting and migrating from Cross-site Scripting (XSS). When generate a new Shopify app through the gem, it's generate few files and one of the files is `app/views/layouts/embedded_app.html.erb` and `app/views/layouts/_flash_messages.html.erb`. This file `lib/generators/shopify_app/install/install_generator.rb` copies the following files to your app.
- `lib/generators/shopify_app/install/templates/embedded_app.html.erb`
- `lib/generators/shopify_app/install/templates/_flash_messages.html.erb` 
The `embedded_app.html.erb` and `_flash_messages.html.erb` contains an inline script tag and it's doesn't play well with CSP, where the first option is to replace the …

Moving the inline js to a js asset file

---

config/locales/en.yml

This is an MVP fix, English-only, for the copy in the ITP flow.
~(the updated yarn lock is unrelated, but should be committed)~

 remove “third-party” from ITP copy

---

example/app/assets/javascripts/flash_messages.js
lib/generators/shopify_app/install/templates/flash_messages.js

Previously in this PR #695 I moved the flash message script block to a separate file to make it play well with [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy). When I moved them to a separate file I had to pass the data for the flash through data attribute.
https://github.com/Shopify/shopify_app/blob/32af7acf93d343d129f69249e7e384b7337845ac/lib/generators/shopify_app/install/templates/_flash_messages.html.erb#L1-L3
In `flash_message.js` I fetch the data and store them in a variable called `flash`
https://github.com/Shopify/shopify_app/blob/32af7acf93d343d129f69249e7e384b7337845ac/lib/generators/shopify_app/install/templates/flash_messages.js#L5
The issue is that there is already a function called `flash` in the same file …

Renaming var flash to flashData

---

CHANGELOG.md
app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/version.rb
package.json

If a user accesses a deep link in an app, the user is redirected to the root url of the app after being granted storage access (or bypassed in an agent that doesn't require it). I found the root cause in SessionsController that was always using the configured root_url to redirect, instead I'm using [this method](https://github.com/Shopify/shopify_app/blob/b41fba031e6e7379580994b9b2aae71f6b53dc41/lib/shopify_app/controller_concerns/login_protection.rb#L132) in LoginProtection.

Retain return_to address after granted_storage_access

---

app/assets/javascripts/shopify_app/storage_access.js
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/enable_cookies.html.erb
lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

I realize that the ITP issues and workarounds are a larger ongoing discussion; however, the problems this PR addresses required us to move our app onto a fork of the gem. I'd like to be able to switch back to the official release as soon as this issue is resolved.
The issue is that in user agents which are subject to the ITP workarounds (Safari 12, Safari WebView in the Shopify POS), the `session[:redirect_to]` value in `ShopifyApp::LoginProtection` is saved prior to the user agent allowing cookies to be set. Once the `fullpage_redirect_to enable_cookies_path` happens at the top level, the original `session[:return_to]` URL is lost. This means that if an unauthenticated user follows a deep link into the app (like from a `More Actions` link or from a POS integration link), then after …

Fixes issue with ITP circumvention and redirecting to requested URL

---

README.md

If you follow the instructions to set up your app, then decide to use nested routes, things don't work as advertised.  See #603.  You need to also know that the engine doesn't render the Shopify Admin UI so you have to route to that *and* you have to know that going to that url triggers the "add your app to shopify" UI.  When you are totally new to this + shopify, these things are not obvious.
Document it.

Clarify how nested routes affect Rails routing

---

app/controllers/shopify_app/callback_controller.rb
app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/controller_concerns/login_protection.rb

`login_url` potentially conflicts with Rails' route helper methods which are auto generated. Since this engine defines a `login` route, `login_url` would be the generated method.
While this doesn't cause problems in normal use cases, if the same route is defined in the main app's route to point to a customized sessions controller (for example), the route helper method `login_url` will take precedence causing redirects to happen *without* the `shop` param.
ie:
```ruby
Rails.application.routes.draw do
get 'login', to: 'sessions#new', as: :login
mount ShopifyApp::Engine, at: '/'
end
```
Even though this is guarding against an uncommon edge case, there's no reason to keep the conflicting method name.
This simply renames it to `login_url_with_optional_shop`.
NOTE: I guess this is a potentially …

Rename `login_url` method to `login_url_with_optional_shop` to avoid ambiguity with Rails' route helper method of the same name

---

CHANGELOG.md
lib/shopify_app/version.rb
package-lock.json
package.json

Ships changes from https://github.com/Shopify/shopify_app/pull/585 into gem v11.0.0.

Packaging for release 11.0.0

---

CHANGELOG.md
README.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/shopify_app/version.rb
test/app_templates/Gemfile
test/app_templates/config/initializers/shopify_app.rb
test/generators/install_generator_test.rb
test/support/generator_test_helpers.rb

The current install generator inserts the Shopify API key and secret into `config/initializers/shopify_app.rb`, which is usually a file that is excluded from gitignore and I imagine results in leaked keys for those that aren't aware of this. Best practice at Shopify and elsewhere is to use ENV variables for these. 
This updates the generator to do so, and this has the benefit of being more compatible with shopify-app-cli.

add dotenv-rails to generator to fetch credentials from env

---

CHANGELOG.md
lib/shopify_app/version.rb
shopify_app.gemspec
test/javascripts/shopify_app/storage_access_test.js

Minor version bump to v11.0.2 which locks the shopfiy_api dependency to `~> 7.0`. Theres breaking change set for version 8 of the shopify_api gem which we want to avoid.
I'll have another PR with a minor version bump that will require version `~> 8.0` (or `<= 8.0.0` ?) of the shopify_api gem next.

bump to v 11.0.2 and lock shopify_api to ~> 7.0

---

README.md
docs/Releasing.md
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/shopify_app/utils.rb
lib/shopify_app/version.rb
shopify_app.gemspec
test/generators/install_generator_test.rb
test/test_helper.rb

Updates the install generator to use the new api_version from v8.0.0 of shopify_api
I debated adding adding config flags for the generator to set the api_version lookup mode and the fetch_known_version on boot, but it doesn't strike me as something you'd want to necessarily configure via a flag. I opted to just add it to the initializer and comment it out in case anyone wants to enable it. 
I wrapped `ShopifyAPI::ApiVersion.fetch_known_versions` in a utility method that just logs out that its fetching the versions and rescues and logs that the versions could not be fetched if it hits an `ActiveResource::ConnectionError`

Update api version handling

---

lib/shopify_app/version.rb
shopify_app.gemspec

The latest version of the `omniauth-shopify-oauth2` gem offers support for user_sessions being serialized.
This PR bumps the version of the gem.

Upgrade version of omniauth-shopify-oauth2 gem

---

lib/generators/shopify_app/install/install_generator.rb
test/app_templates/config/environments/development.rb
test/generators/install_generator_test.rb
test/support/generator_test_helpers.rb

Adds config.hosts [required by Rails 6](https://www.fngtps.com/2019/rails6-blocked-host/).
[Fixes issue brought up in Shopify-App-CLI](https://github.com/Shopify/shopify-app-cli/issues/323)

adds config host for ngrok url

---

lib/shopify_app/version.rb
shopify_app.gemspec

This bumps the browser_sniffer gem to 1.1.3, which included changes to support a new format of user agent strings in POS Next.
I also bumped the version.rb so that dependent apps can pull in this change.

bump browser_sniffer to 1.1.3

---

lib/generators/shopify_app/install/install_generator.rb
test/generators/install_generator_test.rb

This should resolve the PR 822 test failures.
A recent commit added an ngrok entry to Rails.application.config.hosts. This seems to work in Rails 6, but it breaks in Rails 5. I understand the argument for adding ngrok, but there are other proxy services one could use. None of those alternatives are included. A security minded person might argue that this gem should not be doing such an update at all, but rather it should be an exercise left to the user.
The video referenced here: https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-ruby-and-sinatra, must be using Rails 5.x.

FIX: FIX: Adding ngrok to config.hosts in development.rb breaks in Rails v5

---

lib/generators/shopify_app/add_marketing_activity_extension/add_marketing_activity_extension_generator.rb
lib/generators/shopify_app/add_marketing_activity_extension/templates/marketing_activities_controller.rb
lib/shopify_app.rb
lib/shopify_app/controllers/extension_verification_controller.rb
test/generators/add_marketing_activity_extension_generator_test.rb
test/shopify_app/controllers/extension_verification_controller_test.rb

This pr adds generators for building app extensions (though only endpoints at the moment, no related graphql queries or jobs). 
Specifically, this PR currently supports Marketing Activities, but is (hopfully) designed to support other extensions such as Shopify POS and Kit Skills (more info at https://help.shopify.com/en/api/embedded-apps/app-extensions)
I'll put on some comments on other design decisions that were made, though some general goals were; 
- Make sure the setup works for other app extensions 
- Things that are optional to a minimal usage flow do not exist

App Extensions Generators 

---

CHANGELOG.md
lib/shopify_app/version.rb
shopify_app.gemspec

Nothing in the gem uses this dependency. It should be up to each app how they manage their own environment variables.

Remove dotenv from dependencies

---

lib/shopify_app/controllers/extension_verification_controller.rb

Quick fix so that extensions don't validate csrf (because they shouldn't)

Don't do CSRF validation for extensions

---

lib/generators/shopify_app/install/install_generator.rb
test/generators/install_generator_test.rb

#835 remove dotenv but it is still in the generator. I will re-release 11.4.0 with this fix.

remove dotenv-rails from generator

---

README.md
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/shopify_app/configuration.rb
test/app_templates/config/initializers/shopify_app.rb
test/generators/install_generator_test.rb
test/generators/shop_model_generator_test.rb
test/generators/user_model_generator_test.rb
test/shopify_app/configuration_test.rb

As reported in https://github.com/Shopify/shopify_app/issues/757 and https://github.com/Shopify/shopify_app/issues/812, currently our generated initializer running with rails 6 will give this warning:
```
DEPRECATION WARNING: Initialization autoloaded the constant Shop.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shop, for example,
the expected changes won't be reflected in that stale Class object.
This autoloaded constant has been unloaded.
Please, check the "Autoloading and Reloading Constants" guide for solutions.
```
We can avoid issues with the autoloader …

Use a string when setting session_repository

---

lib/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/engine.rb
lib/shopify_app/middleware/same_site_cookie_middleware.rb
test/shopify_app/configuration_test.rb
test/shopify_app/middleware/same_site_cookie_middleware_test.rb

In Chrome 80, the default value of the `SameSite` cookie property will switch from `None` to `Lax` ([more details here](https://docs.google.com/document/d/1d2OTcEHQaRvHaJumPuKyu0pVPre_p_GU5hp_S-Ul_7w/edit)). This means that all iframe'd and cross-origin non-GET requests will not send cookies, meaning that it will break  embedded app functionality (you can try enabling the [SameSite None flag](chrome://flags/#same-site-by-default-cookies) and accessing an embedded app in your admin)
Additionally, `SameSite=None` (which we do not use today) is unfortunately interpreted incorrectly by [specific browsers](https://www.chromium.org/updates/same-site/incompatible-clients), so this PR handles such situations as well.
Added a middleware that sets all app sessions to `SameSite=None` and `secure` if …

Add SameSite=None and secure to App Session

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

This PR bumps the version of shopify_app to 11.6.0. This version makes sure embedded apps will continue to work in Chrome version 80 (https://github.com/Shopify/shopify_app/pull/851).
I decided to make this a minor version as apps will not have to add extra configuration for their app to function correctly in most cases.

Bump version

---

lib/shopify_app/session/session_storage.rb
lib/shopify_app/session/storage_strategies/shop_storage_strategy.rb
lib/shopify_app/session/storage_strategies/user_storage_strategy.rb
test/shopify_app/session/shopify_session_repository_test.rb
test/shopify_app/session/storage_strategies/shop_storage_strategy_test.rb
test/shopify_app/session/storage_strategies/user_storage_strategy_test.rb

fixes #868 
This allows the models used by our session store be named other than Shop and User. This also allows for easier extension in the future.

Allow non shop models for session

---

README.md
lib/generators/shopify_app/home_controller/home_controller_generator.rb
lib/generators/shopify_app/home_controller/templates/shopify_app_ready_script.html.erb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/flash_messages.js
lib/generators/shopify_app/install/templates/shopify_app.js
test/generators/home_controller_generator_test.rb

This PR converts all generated JS to use App Bridge.
- I'm using an unversioned unpkg script tag to load in the library. The only used actions are `TitleBar` and `Toast` create and I don't anticipate the types for these actions changing a lot, but I can switch to a versioned import if we feel that's better.
cc @Shopify/app-bridge 
closes #723

migrate client scripts to App Bridge

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json
shopify_app.gemspec

The latest shopify api gem version is 9.0.0. 
The shopify app gem had a dependency for the api gem that was set to version 8.0.0. This is now updated to 9.0.0
Correspondingly, the ShopifyApp version is updated from 11.7.1 to 12.0.0

Update version to 12.0.0 for breaking ShopifyAPI updates

---

app/assets/javascripts/shopify_app/storage_access.js
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/enable_cookies.html.erb
app/views/shopify_app/sessions/request_storage_access.html.erb
lib/shopify_app/controller_concerns/login_protection.rb
test/javascripts/shopify_app/storage_access_test.js

When a user requests a deep link within the app, and is using a recent version of Safari, the `return_to` address would be lost in the chain of redirects happening for the `enable_cookies` and `granted_storage_access` steps. This PR solves the issue by converting `session[:return_to]` to `params[:return_to]` (where necessary), and ensuring that JS redirects respect the presence of `params[:return_to]` when present.
@tylerball @tanema

Fix return_to address in Safari after enable_cookies/granted_storage_access

---

lib/shopify_app/configuration.rb
test/shopify_app/configuration_test.rb

fixes #874 
The cookie middleware was causing issue with browser testing using capy, so this just disables the middleware for requests in tests

Disable Cookie Middleware in Tests

---

lib/generators/shopify_app/add_marketing_activity_extension/templates/marketing_activities_controller.rb

What are you trying to accomplish with this PR?
Part of: Shopify/marketing-integrations#486
Removing budget in preload form data because not all extension will use that field (for example: Facebook page post). Also the field name (in this case is budget) and currency can be different. We should let the app developers follow the doc and determine what are returned from the app's preload_form_data endpoint.
How does it do it?
Remove budget.
What could go wrong? (if anything)
N/A

[Marketing section] Remove budget property from marketing activities controller

---

lib/shopify_app/middleware/same_site_cookie_middleware.rb

fixes #888 
Our samesite cookie middleware was breaking for ruby 2.3.x and this make it compatible again.

Make compatible with ruby 2.3.x

---

app/assets/javascripts/shopify_app/storage_access.js
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/enable_cookies.html.erb
app/views/shopify_app/sessions/request_storage_access.html.erb
lib/shopify_app/controller_concerns/login_protection.rb
test/javascripts/shopify_app/storage_access_test.js

This reverts commit 301da901461b7fac1c3e0f8108da0ffb9cd61dfb. Introduced in https://github.com/Shopify/shopify_app/pull/873.
Login protection redirects a user to login, needing to request storage access. Due to [this line](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/sessions_controller.rb#L141) and the `return_so` session value, we are never redirected to the granted session storage page, which results in an infinite loop of redirecting back to user login requesting storage access.

Revert "Fix return_to address in Safari after enable_cookies and grated_storage_access"

---

app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/controller_concerns/login_protection.rb

Addresses issues within #897 
This change ensures that users are always redirected to the `granted_storage_access` page, regardless of the presence of a `redirect_to` param. Doing so required persisting the `params[:return_to]` to the `session` after redirecting the browser to the `granted_storage_access` page, so that the behavior of `return_address` will work properly in this case.
Implementing this change revealed an existing issue with the `granted_storage_access` action, where the `shop` param would be appended to the `return_address`, even if query params were already present (ie. given a `return_address` of `/foo?user_id=1234&shop=example.myshopify.com`, the final redirect target (due to the simplistic string concatenation being used) would be …

Fix issue where not redirecting user to granted storage page casues infinite loop

---

lib/shopify_app/engine.rb
lib/shopify_app/middleware/same_site_cookie_middleware.rb

Pairprogramming with @tanema
We learned a couple things while working on this.
If the user does not have a tunnel
- They will receive a csrf error on the main login form
- The omniauth session wont be stored because it wont be on https
We had to do a few things to make sessions more stable
- appropriately cased the `Secure` attribute on the cookie
- Rewrote the middleware to return the status, headers, body to conform to middleware interface
- Moved the middleware higher in the middleware order. We found examples in the wild also editing cookies where the middleware was inserted higher so we copied that and it worked better.
@jenshenny  I know you are implementing this middleware across a bunch of different applications. Do these changes seem to fix any issues you are seeing?

Inserting SameSite middleware higher in stack

---

README.md

The https://github.com/Shopify/shopify_api/ repo has usage examples of specifying the API version you want your app to use, whereas this gem's README only highlights a past migration guide for a particular gem version. We may as well highlight this important concept here and link to more detail.

Update README to highlight shopify_api gem ability to use / switch API versions

---

lib/shopify_app/middleware/same_site_cookie_middleware.rb
test/shopify_app/middleware/same_site_cookie_middleware_test.rb

Changing cookie policy for all cookies (not only those which are relevant to Shopify App) can easily brake other functionalities of someone's app. 
E.g.: We use this gem but our Rails app does other things as well - e.g.: we have Active Admin. Developing on http://localhost:3000 became impossible because of this middleware. 
I had similar problems with rspec tests which were testing session related things (outside ShopifyApp scope). Since feature tests are running without SSL - all those tests broke. 
It seems like many problems would be solved if we would only be fixing cookies on https requests.
Relevant issue: https://github.com/Shopify/shopify_app/issues/911

Do not modify cookie policy on non SSL requests

---

README.md
lib/shopify_app/configuration.rb
test/controllers/sessions_controller_test.rb

During OAuth, the shopify_app initializer template [expects ENV variables](https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/templates/shopify_app.rb#L3). 
This adds a note to read the env vars.

adds note about dot-env gem

---

lib/shopify_app/middleware/same_site_cookie_middleware.rb
shopify_app.gemspec
test/shopify_app/middleware/same_site_cookie_middleware_test.rb

Added SameSite None compatible check to [browser_sniffer](https://github.com/Shopify/browser_sniffer/pull/25/files) gem, thus removing the check and its tests here. Tophatted on my local app.

Bump browser_sniffer to 1.2.0

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json
shopify_app.gemspec

Updates version to 12.0.5. The latest shopify api gem version is 9.0.1 which is also added to the gemspec as a runtime dependency

Update version to 12.0.5

---

CHANGELOG.md
lib/shopify_app/configuration.rb
lib/shopify_app/version.rb
test/controllers/sessions_controller_test.rb

it seems like this check for api key is running when it shouldn't be and causing installation errors. I'd like to remove it for now as it's causing issues for users.

revert warning about api key

---

shopify_app.gemspec

This is now required for gem publishing on our platform

Add allowed_push_host in gemspec

---

CHANGELOG.md
lib/shopify_app/configuration.rb
lib/shopify_app/session/session_repository.rb
test/shopify_app/configuration_test.rb

fix #908 
The issue is that shopify_app loads the session repo class at configuration time to check it's interface. This however breaks reloading and logs a deprecation warning `DEPRECATION WARNING: Initialization autoloaded the constant Shop`
This will now only load the ShopStore or UserStore when they are needed.
@vfonic

Fix for constantization issue in session store

---

README.md

Fix anchor on "Migrating to 13.0.0".
Should be `#migrating-to-1300`, instead of `#migrating-to-13`

Update README.md - Migrating to 13.0.0 anchor

---

lib/generators/shopify_app/add_webhook/templates/webhook_job.rb

resolves #722 
This PR implements the logic suggested by @sshaw. If a shop doesn't exist, will exit with an error message.

Webhook jobs default behavior

---

lib/shopify_app/controller_concerns/login_protection.rb

resolves #773 
This PR adds logic in the  `redirect_to_login` method, in the absence of a query that will be set to `session[:return_to]`
If query is empty:
`session[:return_to] = "#{path}"`  
else will be set to path and query:
`session[:return_to] = `"#{path}?#{query}"`

Add a logic in login_protection.rb not to always display question mark

---

.rubocop.yml

Ruby 2.4 has already reached it's EOL – see https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/.
The target version is debatable, but latest Rubocop versions contain lots of changes related to Ruby 2.7.
This PR kind of depends on https://github.com/Shopify/shopify_app/pull/959.

Update Rubocop TargetRubyVersion to 2.7

---

shopify_app.gemspec

1. The gem spec specifies `s.add_runtime_dependency('shopify_api', '~> 9.0.2')`  
2. The shopify_api gem spec requires `s.required_ruby_version = ">= 2.4"`, see https://github.com/Shopify/shopify_api/blob/v9.0.2/shopify_api.gemspec#L26
Even though ["all support of the Ruby 2.4 series has ended"](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/) in my view we should keep it for compatibility reasons until it causes problems.

bump minimum required Ruby to 2.4

---

.travis.yml

Ruby 2.7 [was released](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/) on 25 Dec 2019 and the latest version is 2.7.1

Test against Ruby 2.7

---

lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/callback_controller_test.rb

The callback controller redirects to the root url after the app has been installed.
Currently, the root url depends on the cookie to fetch the shop and load the app.
In a world without 3rd party cookies, the app has no way of knowing which shop the request is for. By having the Callback Controller add a Shop parameter to the root url, we can load the app and fetch the JWT for the particular shop.

Add shop parameter when redirecting after callback

---

CHANGELOG.md
lib/shopify_app/version.rb

This PR is a release for version 13.1.1, which includes the following changes:
* Adds the shop URL as a parameter when redirecting after the callback
* Bump minimum Ruby version to 2.4
* Bug fixes

Packaging for release 13.1.0

---

shopify_app.gemspec

A [recent change in browser_sniffer](https://github.com/Shopify/browser_sniffer/pull/30) fixes the detection of the `SameSite` attribute compatibility for Chromium OS operating systems.
Previously, cookies for a Chrome OS + Chrome user agents weren't getting the `SameSite=none` and `Secure` attributes.

Update runtime dependency browser_sniffer to 1.2.2

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

The 13.1.1 release includes an update to the `browser_sniffer` dependency. This dependency update will allow the `SameSite=none` and `Secure` cookie attributes to be configured for Chrome OS + Chrome user agents (cookie configuration done in [same_site_cookie_middleware.rb](https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/middleware/same_site_cookie_middleware.rb)).

Packaging for release 13.1.1

---

app/controllers/shopify_app/webhooks_controller.rb
test/integration/webhooks_controller_test.rb

Empty head returns 204 hence kills webhooks.
Shopify expects 200
Might fix #976

fix: Webhook controller returns 204 instead of 200

---

README.md
lib/generators/shopify_app/install/templates/shopify_app.rb.tt
test/generators/install_generator_test.rb

resolves #971 
Update the `shopify_app.rb.tt` from `  config.shop_session_repository = 'ShopifyApp::InMemoryShopSessionStore'
` to `  config.shop_session_repository = 'Shop'
`
also updates the readme to show the renaming of the `shopify_app.rb` to `shopify_app.rb.tt`
cc @tanema

Update shopify_app.rb to match the documentation.

---

app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app.rb
lib/shopify_app/controller_concerns/login_protection.rb
shopify_app.gemspec
test/controllers/sessions_controller_test.rb

The shopify_app is currently vulnerable to open redirect. Open redirect is vulnerability that allows an attacker to redirect a user to an arbitrary domain of the attackers choosing. To read more about open redirect please check this [link](https://portswigger.net/kb/issues/00500100_open-redirection-reflected) or [video](https://www.youtube.com/watch?v=4Jk_I-cw4WE)
1. First clone the repo
2. Create a new Ruby on Rails project
```bash
rails new test-project
```
3. Add the shopify_app gem into your Gemfile and make it point to the local shopify_app
```ruby
gem 'shopify_app', path: 'THE GEM LOCAL PATH'
```
4. Install the gem by running:
```bash
bundle install
```
5. Generate a shopify_app using rails generator
```bash
rails generate shopify_app --api_key <YOUR API KEY>  --secret <YOUR SECRET> …
```

Return to relative paths only

---

app/controllers/shopify_app/callback_controller.rb
config/routes.rb
lib/shopify_app.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/engine.rb
lib/shopify_app/middleware/jwt_middleware.rb
shopify_app.gemspec
test/controllers/callback_controller_test.rb
test/shopify_app/controller_concerns/login_protection_test.rb
test/shopify_app/middleware/jwt_middleware_test.rb

When we receive an OAuth callback with a JWT in the headers, we want to do two things:
1. Validate that the omniauth data matches the JWT data.
2. Persist the token information to the session store.
1. It's a bit of a pain to have two separate callback paths in omniauth. There is a callback_path option, and it does take a block, but I'm a little unclear about how it knows how to start the normal OAuth flow if you use a block for this option. I elected to incorporate the JWT flow into the existing callback path in a backwards-compatible fashion.
2. Omniauth tries to check the state param as part of the callback action and throws an error if the param doesn't exist or doesn't match the param in the session. We won't have a param in the session in this context. So we need to conditionally …

Implement JWT callback endpoint

---

lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

With the new JWT based auth, we won't always have a session. In such cases, `current_shopify_domain` would return a nil value. 
This PR addresses that by fetching the domain from the JWT when it is not present in the session.

Populate current_shopify_domain from the jwt

---

docs/Releasing.md

Updating the release documentation to account for the fact that shopify_app version in package.json would need to be bumped up as well.

Update release doc to account for package.json version bump

---

app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

When the OAuth callback is triggered, there may already be session IDs
in the session, and sometimes those IDs will be for a different shop.
This can happen if the user was previously accessing the app for shop 1
and now accesses the app for shop 2.
These edge cases can result in incorrectly attempting to use a token on
the wrong shop, which fails.
To avoid this scenario, we check that the IDs in the session belong to
the shop that triggered the callback, and clear the values if not.

Clear stale session IDs in callback

---

app/controllers/concerns/shopify_app/require_known_shop.rb
test/controllers/concerns/require_known_shop_test.rb

This PR adds a concern that can be used in an unauthenticated controller.
It does the following
- Adds a before action to check if the passed in shop domain is valid
- Adds a before action to check if the passed in shop is installed
Both the before actions redirect to login in case of failure

Add session token concern

---

.github/workflows/rubocop.yml
.rubocop.yml
Gemfile
lib/shopify_app/middleware/jwt_middleware.rb
test/controllers/concerns/require_known_shop_test.rb
test/shopify_app/configuration_test.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Simply replicated https://github.com/rails/rails/blob/100f7a7f643ae6766f406ccf1e049050199caddc/.github/workflows/rubocop.yml.
Depends on https://github.com/Shopify/shopify_app/pull/959 and https://github.com/Shopify/shopify_app/pull/963.

Add Rubocop to CI

---

test/test_helper.rb

Fixes this warning:
```
Mocha deprecation warning at
/Users/andyw8/.gem/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in
`require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api'
instead of 'mocha/setup'.
```

Fix Mocha deprecation warning

---

docs/Quickstart.md
test/generators/install_generator_test.rb

In #776 we switched to reading the Shopify API key and secret from the environment, but a few references to the old approach were left over.
cc @tylerball

Remove mentions of unused generator flags

---

app/controllers/shopify_app/extension_verification_controller.rb
lib/shopify_app.rb
lib/shopify_app/controller_concerns/app_proxy_verification.rb
lib/shopify_app/controller_concerns/payload_verification.rb
lib/shopify_app/controller_concerns/webhook_verification.rb

This PR resolves #926 
Creates a payload_verifcation.rb and moves the `def hmac_valid?(data)` and `def shopify_hmac`. It then includes this module inside `webhook_verication.rb`.  All tests are passing. 
cc @tanema

Added Payload Verification module

---

lib/generators/shopify_app/install/templates/flash_messages.js

fixes #1007
Removing the event listener prevents flashing messages when navigating with Turbolinks enabled.
This js works only once when using turbolinks and flash messages show only for first full page load.
Removing this line of code will allow it to run on subsequent turbolinks:load and show flash messages on all pages.

Show flash when navigating with turbolinks

---

app/controllers/concerns/shopify_app/authenticated.rb
lib/shopify_app.rb
lib/shopify_app/controller_concerns/csrf_protection.rb
test/controllers/concerns/authenticated_test.rb
test/shopify_app/controller_concerns/csrf_protection_test.rb

With 3p cookies being blocked, Rails will no longer be able to set CSRF tokens. This will result in requests failing with an `invalid CSRF token` error.
When using JWT based auth, a valid signed JWT is as secure than a CSRF token, since we trust that Shopify is the only source that can sign it securely.
This PR introduces a new concern that when included, skips the CSRF check  if we are able to successfully extract the shop domain from the JWT.

Skip CSRF check if a valid JWT is passed in

---

README.md
docs/Quickstart.md

We can now use `bundle add` instead of manually `echo`ing the gem name to `Gemfile`

Simplify installation command with bundle add

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

13.4.0
------
* Skip CSRF protection if a valid signed JWT token is present as we trust Shopify to be the only source that can sign it securely.

Packaging for release v13.4.0

---

app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

I'd like my app to know whether the user token has all the scopes I need, or a subset.
This change will allow me to intercept the `User.store(session, auth_user)` call and do things (in my case I'll store the scope in the DB, and have the UX tell them which scopes they are missing by comparing to `ShopifyApp.configuration.scope`).

Pass along the associated_user_scope

---

CHANGELOG.md
shopify_app.gemspec

Fix dependency on shopify_api to allow all of 9.X

---

lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/sessions_controller_test.rb

When an invalid shop domain is submitted to `SessionsController#create`, it is supposed to display an error like this:
When `allow_jwt_authentication` is enabled, an error is raised instead:
This bug is easily reproducible by setting up shopify_app with `allow_jwt_authentication` set to true, and then navigating to the login page and trying to install with an empty shop domain.
This bug was introduced in #958 because when `allow_jwt_authentication` is enabled in the config, we now try to set the return address with the `current_shopify_domain` included as a parameter. `current_shopify_domain` will raise when there is no currently authenticated shop, so an error will be raised if this flow is triggered from the login page.
We should rescue from this error and fall back to the originally …

Fix ShopifyDomainNotFound when JWT is enabled

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

13.5.0
------
* Added `signal_access_token_required` helper method for apps to indicate access token has expired and that a new one is required

Packaging for release 13.5.0

---

README.md
lib/generators/shopify_app/authenticated_controller/authenticated_controller_generator.rb
lib/generators/shopify_app/home_controller/home_controller_generator.rb
lib/generators/shopify_app/home_controller/templates/index.html.erb
lib/generators/shopify_app/home_controller/templates/unauthenticated_home_controller.rb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/shopify_app.rb.tt
lib/generators/shopify_app/products_controller/products_controller_generator.rb
lib/generators/shopify_app/products_controller/templates/products_controller.rb
lib/generators/shopify_app/shopify_app_generator.rb
test/app_templates/config/initializers/shopify_app.rb
test/app_templates/config/initializers/shopify_app_with_webhooks.rb
test/dummy/config/initializers/shopify_app.rb
test/generators/home_controller_generator_test.rb
test/generators/products_controller_generator_test.rb

> Relates to:
> https://github.com/Shopify/shopify/issues/250171 
> https://github.com/Shopify/shopify/issues/247743
This PR introduces the option to create an unauthenticated home_controller and an authenticated products_controller by specifying the `--with-session-token` option to home_controller generator. It also provides the capability of using JWT-based auth to all future Shopify apps by default if they choose to.
For context, this is the preferred method of creating an app using Shopify's [next-gen auth flow](https://vault.shopify.io/projects/10253). The home_controller needs to be an unauthenticated controller for an app to go to while waiting for authenticated session tokens.
1. By running `rails generate shopify_app` or `rails generate shopify_app:home_controller`:
* The default …

Create optional unauthenticated home_controller generator

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

> https://github.com/Shopify/shopify_app/issues/1039 for more context
This package release allows developers to generate an optional unauthenticated home_controller and a products_controller by specifying the `--with-session-token` flag. This creates an SPA that works with JWT session tokens.

Packaging for release 13.6.0

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

> Context: https://github.com/Shopify/shopify_app/pull/1040
> Context: https://github.com/Shopify/shopify_app/issues/1039
This is a packaging major release for shopify_app 14.0.0. It introduces:
* Bump gemspec ruby dependency to 2.5 (breaking change)
* Bump elliptic from 6.5.1 to 6.5.3
* (Beta) Add `--with-session-token` flag to the Shopify App generator to create an app that is compatible with App Bridge Authentication (originally supposed to be released in 13.6.0)

Packaging for release 14.0.0

---

package.json
yarn.lock

Bumping webpack to version 4.44.1, when the `serialize-javascript` dep was updated past 3.1.0.

Bump webpack version to update serialize-javascript

---

app/assets/javascripts/shopify_app/app_bridge_redirect.js
app/assets/javascripts/shopify_app/redirect.js
app/assets/javascripts/shopify_app/storage_access.js
app/views/shopify_app/sessions/enable_cookies.html.erb
app/views/shopify_app/sessions/request_storage_access.html.erb
app/views/shopify_app/shared/redirect.html.erb
test/javascripts/shopify_app/app_bridge_redirect_test.js
test/javascripts/shopify_app/redirect_test.js
test/javascripts/shopify_app/storage_access_test.js

Fixes https://github.com/Shopify/app-bridge/issues/1410
1. In a project consuming Shopify App Gem, open the gemfile
2. Change the gem path for "shopify_app" to point to the local directory of the Shopify_app repo. Ex. 
> gem "shopify_app", path: "../shopify_app"
3. Ensure that you can build and run the project

Migrate redirect calls to App Bridge

---

app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

There is an issue noticed where the OAuth flow for getting an online (user) token fails to redirect back into the callback endpoint. The online token is eventually retrieved on failed requests to the Shopify API and we exchange an auth code for the online token via App Bridge Auth. However, when making the callback request to with session tokens (as JWTs) in the Authorization header, the post authenticate background jobs are not run, which is undesirable.
This PR ensures that the post authenticated background jobs are triggered after the callback request is made with session tokens in the request.

Ensure post authenticate jobs run after for jwt based callback requests

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

14.4.3
------
* Fix to ensure post authenticate jobs are run after callback requests

Packaging for release 14.4.3

---

.rubocop.yml
lib/generators/shopify_app/controllers/controllers_generator.rb
lib/generators/shopify_app/views/views_generator.rb

This repo isn't locked to a particular RuboCop version, but when running against the latest RuboCop there are some failures.

Fix RuboCop failures

---

.github/ISSUE_TEMPLATE.md
lib/shopify_app/engine.rb

Since shop tokens are passed into the parameters of the jobs and there has been a tendency for people to copy and paste these logs while debugging, it seems safest to redact the arguments from the jobs so that this will not happen accidentally in the future.
This will patch ActiveJob::Logging::LogSubscriber for rails < 6.1 and use `log_arguments = false` for rails >= 6.1

Disable logging args in ShopifyApp jobs

---

lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Boolean header value for the custom HTTP header `X-Shopify-API-Request-Failure-Unauthorized` was giving the following error in `cardreader-giveaway` app.
This was because the webrick handler in the rack gem iterates over the key/values of the HTTP headers in the response and calls `.split(...)` on the values. The value of the `X-Shopify-API-Request-Failure-Unauthorized` is a `TrueClass` instance, thus the above error.
This PR switches the boolean header value to a string. 

Switch boolean HTTP header value to string

---

lib/generators/shopify_app/install/templates/shopify_app.rb.tt
test/generators/install_generator_test.rb

Thoughts on making it explicit when the key is not set when it is expected for it to be present so it fail fast?

Enforce presence of application key and secret during initialization

---

lib/generators/shopify_app/install/install_generator.rb
test/generators/install_generator_test.rb

Originally added here: https://github.com/Shopify/shopify_app/pull/802
It took me a long while to understand that \h in ruby is not the same as some other languages.....
> /\h/ - A hexdigit character ([0-9a-fA-F])
https://ruby-doc.org/core-2.7.1/Regexp.html
That being said, paid ngrok account and use more characters in their premium domains.
Also adding some `\.` to make sure we treat them as dots and not wildcards.

Update ngrok template

---

lib/shopify_app/session/jwt.rb
test/shopify_app/session/jwt_test.rb

It seems that we've introduced a slight bug for developers who are developing with the shopify_app gem.
Now that core returns the sub field of a jwt as a string, the following validation fails for any app that is developing with online access tokens using shopify_app: https://github.com/Shopify/shopify_app/blob/2401342e466c35f1617ebc541a0093a3ade351aa/app/controllers/shopify_app/callback_controller.rb#L87
In this scenario, the associated_user_id parsed by omniauth remains an Integer, but the jwt_shopify_user_id parsed by our middleware is now a String. There is a type mismatch. The easiest solution for this is to cast the sub field as an integer in our middleware to ensure that everything still works with omniauth as intended (I think this is fine because it's the developer's prerogative …

Update jwt#shopify_user_id to return an integer

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

15.0.1
------
* Allow JWT session token `sub` field to be parsed as a string

Packaging for release 15.0.1

---

lib/shopify_app/session/jwt.rb

New Github Actions for the CI introduces an updated version of Rubocop. Originally the Rubocop check used (I think) 0.93.1, but now we're using 1.5.2.

Fix rubocop error

---

README.md

I've moved the API key notes to before the instruction to run the generator. Otherwise, the user will run into an error due to the missing env vars.
I've also updated the guidance to suggest dotenv-rails rather than dotenv, since it makes configuration simpler.

Update environment variable guidance in README

---

CHANGELOG.md
Gemfile.lock
README.md
shopify_app.gemspec

Rails 6.1 not yet supported

---

CHANGELOG.md
README.md
lib/generators/shopify_app/install/templates/shopify_app.rb.tt
test/generators/install_generator_test.rb

In https://github.com/Shopify/shopify_app/pull/1097 a change was required that the Shopify environment variables were present. As this code is in an initializer, it also runs when the generators run, but at that point in time the environment variables may not yet be available (e.g. because dotenv-rails hasn't been added yet).
Based on a suggestion in https://stackoverflow.com/a/32789186, we can check if the initializer is running from a generator or not.

Don't run app config for generator

---

.github/workflows/release.yml

Follow up https://github.com/Shopify/shopify_app/pull/1138 to use the `actions/create-release@v1` instead of the hub cli. 
Forgot this is testable on a fork! https://github.com/mllemango/shopify_app/releases/tag/v17.0.3

Use actions instead of hub cli

---

app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

Fixes https://github.com/Shopify/shopify_app/issues/1128
We have noticed that the callback controller was fetching a token based on the session object for post perform jobs. This is not necessary as the offline and/or online tokens can be retrieved via the auth hash.

Ensure offline and online tokens are fetched via available auth hash

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

17.0.2 (January 20, 2021)
------
* Fix failing script tags and webhooks installs after performing OAuth [#1151](https://github.com/Shopify/shopify_app/pull/1151)

Packaging for release 17.0.2

---

CHANGELOG.md
lib/generators/shopify_app/install/templates/shopify_app.rb.tt

Once we started skipping the initializer for generators (#1144), we ended up in a situation where the default config generated by the template and the default values in `ShopifyApp` configuration had opposing values, therefore causing new apps to generate an authenticated `home_controller.rb` file rather than its unauthenticated counterpart because cookie auth is still the default.
This PR addresses that by only skipping the values that depend on environment variables when running generators so that the actual config of the app still applies on generator runs and creates consistent apps.

Only skip environment variables from initializer for generators

---

app/controllers/concerns/shopify_app/ensure_authenticated_links.rb
test/controllers/concerns/ensure_authenticated_links_test.rb

> Fixes the issue brought up by a partner https://github.com/Shopify/shopify_app/pull/1118#issuecomment-765350708
In a world without cookies, an embedded app needs to handle attempted access to protected resources both in an embedded and non-embedded state. This PR fixes the scenario where `ShopifyApp::LoginProtection::ShopifyDomainNotFound` is raised when:
* The app is in a non-embedded state
* No shop parameter is passed in
* The app is unauthenticated
* The browser does not support 3p cookies (and subsequently does not have a 1p cookie saved on its domain with a sample `shop` domain)
In this scenario, rather than raise an exception, we should redirect to the app's `login_url`.

[Bug fix] Redirect EnsureAuthenticatedLinks to login page if shop domain not found

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

17.0.4 (January 25, 2021)
----------
* Redirect user to login page if shopify domain is not found in the `EnsureAuthenticatedLinks` concern [#1158](https://github.com/Shopify/shopify_app/pull/1158) 

Packaging for release 17.0.4

---

app/controllers/shopify_app/callback_controller.rb
app/controllers/shopify_app/sessions_controller.rb
test/controllers/callback_controller_test.rb
test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Currently, new apps using `shopify_app` have session tokens enabled and cookies based auth disabled by default. The problem is that even at the top level actions where cookies are accessible and appropriate to use, `LoginProtection` gates it's usage in `user_session_by_cookie` and `shop_session_by_cookie` using the `allow_cookie_authentication` setting. This has led to calls for the `user_session` and `shop_session` resulting in `nil`, leading the app to falsely believe that it doesn't have an offline and/or online token.
1. **[/login]** Initiate OAuth to fetch the offline/shop access token
1. Goes through OAuth process
1. **[/callback]** Store the offline access token
1. **[/callback]** Respond with [redirect to login to fetch online …

Fix omniauth strategy not being set correctly for apps using session tokens

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

17.0.5 (January 27, 2021)
----------
* Fix omniauth strategy not being set correctly for apps using session tokens [#1164](https://github.com/Shopify/shopify_app/pull/1164)

Packaging for release 17.0.5

---

test/controllers/sessions_controller_test.rb

We went from `:shopify` -> `:shop_id` in version 13, but we had tests that still passed despite using the old name. This tidies up those tests. It also removes one test that always passed because the exceptional behaviour it was testing was actually the default behaviour that always happened.

Tidy up tests with useless assertions

---

README.md
lib/generators/shopify_app/shop_model/shop_model_generator.rb
lib/generators/shopify_app/shop_model/templates/db/migrate/add_shop_access_scopes_column.erb
lib/generators/shopify_app/user_model/templates/db/migrate/add_user_access_scopes_column.erb
lib/generators/shopify_app/user_model/user_model_generator.rb
test/generators/shop_model_generator_test.rb
test/generators/user_model_generator_test.rb

Embedded apps using session tokens do not automatically handle changes in access scopes for offline and online tokens. In order to handle changes to access scopes requested, we need to store the access scopes of access tokens.
This PR creates optional database migrations in the generators to allow apps to store access scopes in the Shop and User models.  
- You should be prompted to add `AddShopAccessScopesColumn` migration
- Prompt yes to generate migration
- Run `rails db:migrate` to successfully add new column to Shop model
- You should be prompted to add `AddUserAccessScopesColumn` migration
- Prompt yes to generate migration
- Run `rails db:migrate` to successfully add new column to User model

Add access scopes to Shop and User model generators

---

Gemfile.lock
README.md
app/controllers/shopify_app/callback_controller.rb
lib/generators/shopify_app/shop_model/templates/shop.rb
lib/generators/shopify_app/user_model/templates/user.rb
lib/shopify_app.rb
lib/shopify_app/session/in_memory_shop_session_store.rb
lib/shopify_app/session/in_memory_user_session_store.rb
lib/shopify_app/session/shop_session_storage_with_scopes.rb
lib/shopify_app/session/user_session_storage_with_scopes.rb
shopify_app.gemspec
test/controllers/callback_controller_test.rb
test/generators/shop_model_generator_test.rb
test/generators/user_model_generator_test.rb
test/shopify_app/session/session_repository_test.rb
test/shopify_app/session/shop_session_storage_with_scopes_test.rb
test/shopify_app/session/user_session_storage_with_scopes_test.rb
test/support/session_store_strategy_test_helpers.rb

Embedded apps using session tokens do not automatically handle changes in access scopes for offline and online tokens. In order to handle changes to access scopes requested, we need to store the access scopes after successfully completing OAuth flows.
On successful completion of OAuth, apps will now store the access scopes of an access token in `ShopifyApp::ShopSessionStorageWithScopes` and `ShopifyApp::UserSessionStorageWithScopes`.
- Appropriate Shop record should have `access_scopes` with the expected values
- Appropriate User record should have `access_scopes` with the expected values

Store access scopes after successful OAuth

---

README.md
app/controllers/concerns/shopify_app/shop_access_scopes_verification.rb
app/controllers/shopify_app/callback_controller.rb
docs/shopify_app/handling-access-scopes-changes.md
docs/shopify_app/session-repository.md
lib/generators/shopify_app/home_controller/templates/home_controller.rb
lib/generators/shopify_app/home_controller/templates/unauthenticated_home_controller.rb
lib/generators/shopify_app/install/templates/shopify_app.rb.tt
lib/generators/shopify_app/install/templates/shopify_provider.rb.tt
lib/shopify_app.rb
lib/shopify_app/access_scopes/noop_strategy.rb
lib/shopify_app/access_scopes/shop_strategy.rb
lib/shopify_app/access_scopes/user_strategy.rb
lib/shopify_app/configuration.rb
lib/shopify_app/omniauth/omniauth_configuration.rb
lib/shopify_app/utils.rb
test/controllers/callback_controller_test.rb
test/controllers/concerns/shop_access_scopes_verification_test.rb
test/generators/home_controller_generator_test.rb
test/shopify_app/access_scopes/noop_strategy_test.rb
test/shopify_app/access_scopes/shop_strategy_test.rb
test/shopify_app/access_scopes/user_strategy_test.rb
test/shopify_app/configuration_test.rb
test/shopify_app/omniauth/omniauth_configuration_test.rb
test/support/access_scopes_strategy_test_helpers.rb
test/test_helper.rb

Embedded apps using session tokens do not automatically handle changes in access scopes for offline and online tokens. In order to handle changes to access scopes requested, we need to determine when to trigger OAuth to grant new scopes.
This PR introduces access scopes strategies, which will be used in the gem to determine whether new scopes need to be granted for a shop and/or user. The following strategies are set by default as part of our `ShopifyApp::Configuration`:
```ruby
ShopifyApp.configuration.shop_access_scopes_strategy = ShopifyApp::AccessScopes::ShopStrategy
ShopifyApp.configuration.user_access_scopes_strategy = ShopifyApp::AccessScopes::UserStrategy
```
It should be noted that `shop_access_scopes_strategy` and `user_access_scopes_strategy` are read-only.
These strategies are …

Use access scopes strategies to handle changes to scopes requested by app

---

.github/workflows/build.yml

This wasn't running for external contributors, e.g. https://github.com/Shopify/shopify_app/pull/1187

Enable CI build GitHub Action to run on pull requests on a fork

---

app/controllers/shopify_app/callback_controller.rb

After upgrading to v17.1.0 I noticed that controller tests are not passing. I use OmniAuth mock in controller tests to login as shop:
```ruby
class ActionDispatch::IntegrationTest
def login(shop)
OmniAuth.config.test_mode = true
OmniAuth.config.add_mock(:shopify,
provider: 'shopify',
uid: shop.shopify_domain,
credentials: { token: shop.shopify_token })
Rails.application.env_config["omniauth.auth"] = OmniAuth.config.mock_auth[:shopify]
get "/auth/shopify"
follow_redirect!
end
end
```
This code started raising an error:
Changes the syntax for fetching access_scope in CallbackController to be tolerant to empty `auth_hash['extra']`.
`Hash#dig` is supported since Ruby 2.3 so it shouldn't break anything (since the library requires ruby >= 2.5).

Fetch access scope via #dig in callback controller

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

17.1.1 (March 12, 2021)
----------
* Fix issues with mocking OmniAuth callback controller tests (#1210)[https://github.com/Shopify/shopify_app/pull/1210]

Packaging for release 17.1.1

---

docs/shopify_app/handling-access-scopes-changes.md

Update instructions for how to setup `reauth_on_access_scope_changes` in config and controller to make it simpler for others to use this great new functionality. Please see https://github.com/Shopify/shopify_app/issues/1211 for more details.

Update instruction for how to setup `reauth_on_access_scope_changes`

---

.github/CODEOWNERS

Add App Foundations team as code owners
The responsibility of maintaining the Shopify App gem has also been added to the App Foundations team.

Add App Foundations as code owners of shopify_app

---

test/controllers/sessions_controller_test.rb
test/integration/webhooks_controller_test.rb

> Closes https://github.com/Shopify/shopify_app/issues/1218
**TL;DR** We've been seeing the following failures intermittently on builds for a few weeks now:
1. `NoMethodError: undefined method 'shopify_app_path' for #<Module:xyz>`
2. `NoMethodError: undefined method 'root_path' for #<Module:xyz>`
On closer investigation, the two Engine controllers that keep failing are `sessions_controllers` and `webhooks_controller`. 
**One fix that appears to work is to reload the Rails routes between each test.**
---
I'm not 100% sure what the order of operations are for engines when they mount, but I believe that these two controllers have difficulty finding the following routes mounted on the dummy app between tests:
https://github.com/Shopify/shopify_app/blob/129cea927861a21be2f5d22f6872fc1ff3658667/ …

Fix intermittent engine controller test failures

---

test/controllers/concerns/ensure_authenticated_links_test.rb
test/controllers/concerns/require_known_shop_test.rb
test/controllers/sessions_controller_test.rb
test/integration/webhooks_controller_test.rb
test/shopify_app/controller_concerns/csrf_protection_test.rb
test/test_helper.rb

> Fixes (hopefully) https://github.com/Shopify/shopify_app/issues/1218
> This is a follow up to #1225 
There are still intermittently failing tests, but this time on different files than before. See the recent failing build: https://github.com/Shopify/shopify_app/pull/1221/checks?check_run_id=2175638755
The one thing all of these test files have in common is that they invoke `@routes = ShopifyApp::Engine.route` in their setup blocks, similar to the test files in #1225 
This PR adds logic to reload the Rails routes on all such test files.
Test `bundle exec rake test` on ruby 2.7, 2.6, and 2.5 repeatedly. I've noticed that the files changed in this PR are the ones consistently failing across each ruby version, except with different files failing in 2.6 vs 2.7. 
1. I have not yet analyzed …

Reload Rails routes before each engine test

---

docs/shopify_app/session-repository.md

Fix typo of `ShopifyApp::OmniAuthConfiguration` in [docs/shopify_app/session-repository.md](https://github.com/Shopify/shopify_app/blob/974f294a12789b8bb24ddc0e2476e9b7ef7ecdb8/docs/shopify_app/session-repository.md#migrating-from-shop-based-to-user-based-token-strategy).
The correct class name is [here](https://github.com/Shopify/shopify_app/blob/974f294a12789b8bb24ddc0e2476e9b7ef7ecdb8/lib/shopify_app/omniauth/omniauth_configuration.rb#L4).

Fix typo of ShopifyApp::OmniAuthConfiguration in docs/shopify_app/session-repository.md

---

lib/generators/shopify_app/install/templates/embedded_app.html.erb

With App Bridge 2.0, we need to lock all existing (for this minor release) app developers to `app-bridge@1` using the CDN. By default, CDN will serve app bridge 2.0, which is breaking.
* Tophat this by creating a new app (or using an existing app) and ensure you don't get served app-bridge 2.0 in the embedded_app layout

Bug fix: lock app-bridge to < 2 for this minor release

---

docs/Troubleshooting.md
lib/generators/shopify_app/home_controller/templates/index.html.erb
lib/generators/shopify_app/home_controller/templates/unauthenticated_home_controller.rb
lib/generators/shopify_app/install/templates/embedded_app.html.erb
lib/generators/shopify_app/install/templates/shopify_app.js
lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/callback_controller_test.rb

> ⚠️ This is a breaking change
Support App Bridge 2.0 in shopify_app.
- Import local version of this branch to new app
- Ensure that app runs as expected in Admin
Ensure migration strategy is followed as per the [guide](https://shopify.dev/tutorials/migrate-your-app-to-app-bridge-2).

Support App Bridge 2.0 in shopify_app

---

lib/generators/shopify_app/home_controller/templates/home_controller.rb
lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/callback_controller_test.rb

This PR fixes a bug relating to recent changes to support App Bridge 2.0. For apps that rely on 3p cookies, the `host` parameter is not being passed in, which leads to failure to load App Bridge. This PR ensures that the host parameter is passed after completing the OAuth flow.
- The [return address](https://github.com/Shopify/shopify_app/pull/1259/files#diff-d73da7552f28e00cec3da61e695cfe70a8b49c4e2c403bc7062863bbf9fa185cR226) after completing OAuth

Bugfix: Pass host param into return address regardless of apps's auth config

---

CHANGELOG.md
app/assets/javascripts/shopify_app/post_redirect.js
app/views/shopify_app/shared/post_redirect_to_auth_shopify.html.erb
lib/shopify_app/engine.rb

This change adopts an earlier implementation we'd explored for the POST redirect page. Rather than embed the JS in an inline `script` tag, we're shipping it in a separate file.
This is an immediate response to an issue that was flagged in 18.0.0. This fix introduces a race condition for local dev environments. We don't love that, but it's more important to us to make sure that:
1. Our latest release doesn't have a feature that might be incompatible with a consumer's CSP
1. We still have a release out there that unblocks devs who want to update to the latest omniauth
* Move JS for POST redirect back to separate file
* Add file to asset manifest
* Install the gem on an existing app and verify that the oauth install flow still works
* NOTE: If your local dev env uses the `cookie_store` …

Move js for POST redirect back to separate file

---

Gemfile.lock
shopify_app.gemspec
test/controllers/sessions_controller_test.rb

There was an update to our React Native Shopify POS `user_agent` `string`:
```ruby
user_agent_from_android_device = "com.jadedpixel.pos Shopify POS/4.23.0/Android/12/google/Pixel 5/production MobileMiddlewareSupported"
user_agent_from_services_internal_android_SDK = "com.jadedpixel.pos Shopify POS/4.24.0-mal+30112/Android/9/google/Android SDK built for x86/development MobileMiddlewareSupported"
```
These were not recognised by BrowserSniffer gem. [I've made the fix to the gem](https://github.com/Shopify/browser_sniffer/pull/36) and now we need to bump the gem in `shopify_app` for the changes to take effect.
Tophat-able through test cases.
<details><summary>Before gem bump</summary>
</details>
<details><summary>After gem bump</summary>
</details>
Now that I could add this update to Stocky, …

Bump BrowserSniffer gem

---

docs/shopify_app/engine.md
docs/shopify_app/script-tags.md
docs/shopify_app/webhooks.md

Our documentation is using arbitrary domain names in its code snippets and to eliminate the risk of having an app developer miss-configuring their application with these, we should use invalid hosts in our examples.
I've used `example.com` which is a reserved domain: https://en.wikipedia.org/wiki/Example.com
1. Any typo?
2. Did I miss any other arbitrary domain names that we use in our `.md` files?

Update arbitrary domain names used in our documentation to a reserved second level domain name

---

lib/generators/shopify_app/install/install_generator.rb
test/generators/install_generator_test.rb

I've changed the regexp used to whitelist requests. By default ngrok urls contains `-` but the regexp used at the moment only allows letters and numbers.
With this change requests to URLs like https://cee0-212-222-187-147.ngrok.io work
This issue was reported in #1182

Fix #1182 | Changed regexp to match standard ngrok urls

---

app/controllers/concerns/shopify_app/ensure_authenticated_links.rb
test/controllers/concerns/ensure_authenticated_links_test.rb

`EnsureAuthenticatedLinks` is currently broken and doesn't pass `host` header for `AppBridge 2`. As a result, all deep links in the app are broken.
I added the missing "host" header to redirect to the splash page to fix it.

Make EnsureAuthenticatedLinks compatible with AppBridge 2

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

This is a patch release that includes the following change:
* Use App Bridge client for redirect [#1247](https://github.com/Shopify/shopify_app/pull/1247)
* Replaces deprecated EASDK with App Bridge when redirecting out of an embedded iframe.

Packaging for release v18.0.4

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

This is a patch release that includes the following change:
* Fix bug causing `unsafe-inline` CSP violation. [#1362](https://github.com/Shopify/shopify_app/pull/1362)

Packaging for release v18.1.1

---

Gemfile.lock

This PR is just bumping the `shopify_api` dependency to the latest version.

Bumping shopify_api to v10.0.1

---

Gemfile.lock

Bumping `shopify_api` to v10.0.2 to fix the sorbet dependency mismatch.

Bumping shopify_api to v10.0.2

---

CHANGELOG.md
app/controllers/shopify_app/callback_controller.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/session/session_repository.rb
lib/shopify_app/session/user_session_storage_with_scopes.rb
test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/shopify_app/controller_concerns/login_protection_test.rb
test/shopify_app/session/session_repository_test.rb
test/shopify_app/session/shop_session_storage_test.rb
test/shopify_app/session/user_session_storage_test.rb
test/shopify_app/session/user_session_storage_with_scopes_test.rb
test/test_helper.rb

We unintentionally dropped some important functionality from this gem as part of our updates of `shopify_api`: the OAuth flow was expected to create _both_ an offline and an online tokens when using user storage, but the updated flow was only doing one of them.
This PR walks that back by adding back the behaviour of first getting an offline token, then an online token, then completing the OAuth process, but only in cases where online tokens are required - offline flows remain the same (only a shop is added to the DB).
1. Create a new app with the CLI
2. Run `rails generate shopify_app:user_model`
3. Add `config.user_session_repository = 'User'` in shopify_app.rb
4. `shopify app serve` => go through login
1. Does oauth work for online tokens?
2. Does oauth work for offline tokens?
Before …

Fixing online token creation

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

This is a patch release on the v18 release line that includes the following change that was back-ported from latest main/v19:
* [Bump browser_sniffer](https://github.com/Shopify/shopify_app/pull/1434)

Packaging for release v18.1.3

---

Gemfile.lock
shopify_app.gemspec

Bumps `browser_sniffer` to `2.0.0` to receive an update on [POS user agent detection](https://github.com/Shopify/browser_sniffer/pull/38) I've recently published.
Open to suggestions on how I can add a test case for this. Previous gem bumps here added a test to `sessions_controller` [but the test passes regardless of what user-agent is passed through](https://github.com/Shopify/shopify_app/pull/1331/files#diff-0ebf4c65ae927de1d02650f4caa7f2810e14eb64201b7570cb30939f0ee38719). 
A method that checks for POS browser name is [also marked private and not used anywhere](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/itp.rb#L29).

Bump browser_sniffer

---

CHANGELOG.md
app/controllers/shopify_app/sessions_controller.rb
config/routes.rb
lib/shopify_app/configuration.rb
test/routes/callback_routes_test.rb
test/routes/sessions_routes_test.rb

In some cases, the Shopify routes might be mounted under a custom `root_url`, when the `Engine` is not mounted at `/`. Assuming that `root_url` is expected to match the root URL for the `Engine`, this PR adds support for customizing both the OAuth login and callback routes so that they can be arbitrarily determined by the app.
The goal here is for this to preserve the current behaviour by default, so I just wanted to make sure that assumption about `root_url` is actually correct.
Tested via unit tests and by using the gem locally on a CLI-generated app.
1. Is this changing any existing behaviour?
2. Are the test cases covering enough scenarios?
3. Is it the right thing to strip out `root_url` from the URLs when setting up the routes? That is where the assumption about `root_url` comes …

Allow custom OAuth URLs

---

README.md

Reported by @lilypustovyk.
The Rails version in the badge is hard-coded in the README and is incorrect.
Keeping this badge up-to-date is a maintenance burden, and I don't think it really adds much value.

Remove stale hard-coded Rails version badge

---

CHANGELOG.md
lib/shopify_app/jobs/webhooks_manager_job.rb

This changes the `perform()` method of `WebhooksManagerJob` to accept-and-ignore additional keyword arguments. 
One of the things we noticed during upgrade from v18 to >=v19 is that https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/jobs/webhooks_manager_job.rb#L9 used to take a webhooks parameter to the function, but no longer does. This manifests in errors where webhooks that have been registered with Core pre-upgrade include that parameter on delivery, and so error out.
I plan on porting this fix to v19.1 branch and v20 branch along with `main`, since I think it's a useful change and removes a gotcha for upgrades.
- Install a version of the app that is on an older (v18) version which has webhook(s) registered. For example, a `app/uninstalled` handler;
- Upgrade the …

Ignore extra kwargs on `perform()` in WebhooksManagerJob

---

CHANGELOG.md
README.md
docs/Upgrading.md

As part of the Shopify API and app template strategy, the public repos were renamed to provide a more consistent naming convention.
Where applicable, this PR renames the following repos to match the new naming convention.
- `Shopify/shopify_api` -> `Shopify/shopify-api-ruby`
- `Shopify/shopify-node-api` -> `Shopify/shopify-api-node`
- `Shopify/shopify-php-api` -> `Shopify/shopify-api-php`
- `Shopify/shopify-app-node` -> `Shopify/shopify-app-template-node`
- `Shopify/shopify-app-php` -> `Shopify/shopify-app-template-php`

Update API repo links (post Editions 2022 tidy-up)

---

test/controllers/callback_controller_test.rb
test/controllers/concerns/ensure_billing_test.rb
test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/generators/home_controller_generator_with_execution_test.rb
test/generators/products_controller_generator_with_execution_test.rb
test/shopify_app/managers/scripttags_manager_test.rb
test/shopify_app/session/user_session_storage_test.rb
test/shopify_app/session/user_session_storage_with_scopes_test.rb
test/support/session_store_strategy_test_helpers.rb
test/utils/rails_generator_runtime.rb

Moves call to `setup_context` from tests to `ShopifyAppConfigurer`, therefore globally set before each test case.
`setup` in some test suites need to issue a call to `setup_context` if the `ShopifyApp` configuration changes.

Move setup_context to ShopifyAppConfigurer

---

test/shopify_app/controller_concerns/login_protection_test.rb

Related #1459 and https://github.com/Shopify/shopify-api-ruby/issues/978
Adds tests to ensure that API key rotation #1459 is supported by passing both old and new secrets in the unit tests. This PR itself has no logic changes as the issue itself was addressed in `shopify-api-ruby` repo (`shopify_api` gem) by https://github.com/Shopify/shopify-api-ruby/issues/978.
Run `bundle exec rake test TEST=test/shopify_app/controller_concerns/login_protection_test.rb`.
Any concern on adding `ShopifyAPI::Context.setup` call in the unit tests? I believe passing a *real* JWT through `ShopifyAPI::Utils::SessionUtils.load_current_session` gives us extra confidence when upgrading `shopify_api` gem in the future.

Tests to ensure `current_shopify_session` validates session token using old and new secrets

---

CHANGELOG.md
Gemfile.lock
app/controllers/concerns/shopify_app/require_known_shop.rb
app/controllers/concerns/shopify_app/shop_access_scopes_verification.rb
app/controllers/shopify_app/callback_controller.rb
app/controllers/shopify_app/sessions_controller.rb
docs/Upgrading.md
lib/generators/shopify_app/home_controller/templates/unauthenticated_home_controller.rb
lib/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/controller_concerns/redirect_for_embedded.rb
lib/shopify_app/controller_concerns/sanitized_params.rb
shopify_app.gemspec
test/controllers/callback_controller_test.rb
test/controllers/concerns/ensure_billing_test.rb
test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/generators/home_controller_generator_with_execution_test.rb
test/generators/products_controller_generator_with_execution_test.rb
test/shopify_app/configuration_test.rb
test/shopify_app/managers/scripttags_manager_test.rb
test/shopify_app/session/user_session_storage_test.rb
test/shopify_app/session/user_session_storage_with_scopes_test.rb
test/support/session_store_strategy_test_helpers.rb
test/utils/rails_generator_runtime.rb

We want to improve OAuth experience by:
- Making it faster
- Reducing the amount of screen flicker.
Note, this PR will require https://github.com/Shopify/shopify-api-ruby/pull/1002 to be merged first, the TODO's updated accordingly, before it can be merged itself
Fixes https://github.com/Shopify/first-party-library-planning/issues/393
To be documented
1. Top-level: App installation from the app store 
1. Top-level: Token refresh scopes change (grant screen present)
1. Top-level: Token refresh no scopes change (grant screen skipped)
1. Iframe: Token refresh scopes change (grant screen present)
1. Iframe:Token refresh no scopes change (grant screen skipped)
- Update `README.md`, if appropriate - not applicable
- …

Process embedded parameter to optimize OAuth

---

.github/workflows/stale.yml

Creates a GitHub action to close stale issues. This will find and close stale issues at 1:30 UTC everyday.
closes [this issue](https://github.com/Shopify/first-party-library-planning/issues/423)
Right now we add the label "stale" to any issues that have no activity for two years. After 14 days of being a stale issue it will close.
1. Do we like the time frames?
2. Do we like the messages?

Close Stale Issues

---

CHANGELOG.md
lib/shopify_app/managers/webhooks_manager.rb
test/shopify_app/managers/webhooks_manager_test.rb

As discussed in #1492 , the Ruby API is [expecting the webhook path](https://github.com/Shopify/shopify-api-ruby/blob/7a08ae9d96a7a85abd0113dae4eb76398cba8c64/lib/shopify_api/webhooks/registrations/http.rb#L12) instead of webhook address.
This will deduce the webhook's path if the engine is configured with the deprecated `address` attribute.
To make the `:address` -> `:path` webhook 
1. Create a new rails app
2. Install this gem in Gemfile:
```ruby
gem "shopify_app", git: 'https://github.com/shopify/shopify_app.git', branch: 'nelsonwittwer/deduce_path'
```
3. Bundle install
4. run the generator `rails g shopify_app` in the directory of your new app
5. run the generator `rails g shopify_app:add_webhook --topic orders/create --path webhooks/create_orders` to generate a webhook
6. Modify the …

Deduce webhook path from address

---

README.md
docs/Quickstart.md

This commit removes duplicate sections on how to set up a tunnel to allow OAuth redirect during development, makes the one remaining section clearer and fixes the link it contains to a shopify.dev tutorial.
This gem's docs previously gave instructions to setup a Cloudflared tunnel, but then directed users to follow a section of a shopify.dev tutorial which started with setting up an Ngrok tunnel instead before moving on to adding the redirect URI to the partners dashboard.
After this change, the docs link first to the shopify.dev tutorial section and include a note after for using Cloudflared should the user wish.

Improve OAuth tunnel docs

---

CHANGELOG.md
lib/shopify_app/controller_concerns/ensure_billing.rb

Fixes the method signature of `StandardError` when we call `super`
In a Rails app that uses this branch of the gem (`gem "shopify_app, git: "git@github.com:Shopify/shopify_app.git", "branch: nelsonwittwer/billing_error"`) ensure that you can instantiate a `BillingError`
🎩 
```ruby
irb(main):001:0> ShopifyApp::EnsureBilling::BillingError.new("Error while billing the store", [{"field"=>nil, "message"=>"message"}])
=> #<ShopifyApp::EnsureBilling::BillingError: Error while billing the store>
```
I was able to do instatiate an error without it complaining as reported in [this issue](https://github.com/Shopify/shopify_app/issues/1484)

fix method signature of super

---

CHANGELOG.md
lib/shopify_app/session/user_session_storage.rb
test/shopify_app/session/user_session_storage_test.rb

We had updated the `UserSessionStorageWithScopes` class to fix an issue where the type of the `user` param was incorrect, but the same issue was present in `UserSessionStorage`. This PR fixes that to properly call `user.id` to access the `AssociatedUser` property.
You'll need to create an app with a few conditions:
- It has User sessions (`rails g shopify_app:user_model`)
- Answer `n` when prompted if you want to add user scopes
- Make sure the `User` model is using the `include ShopifyApp::UserSessionStorage` concern (not `ShopifyApp::UserSessionStorageWithScopes`
- Set `config.reauth_on_access_scope_changes = false` in the `shopify_app` initializer
- Set `config.user_session_repository = "User"`
Before this branch, that would lead into an infinite auth loop. With this fix, the app …

Fix user session storing without scopes

---

docs/Troubleshooting.md
docs/Upgrading.md

Loving your upgrade doc suggestions! As I've been helping others upgrade and reading through PRs of internal apps that upgraded I suggest the following to your PR:
1. Move your excellent debugging tips to the `Troubleshooting` section to be (what I think) more discoverable. I think your advice is applicable to more than just upgrading and thought worth moving to that section.
2. Until we can automatically warn people about `Authenticated` vs `RequireKnownShop` I felt it important to drop a note explaining the two concerns and how they compete with each other.
3. I felt the The change from 18 -> 19+ needed a little more context as to why the big changes were made to move around the auth logic. 
These are just suggestions, let me know what you think!

Upgrade doc suggestions

---

docs/shopify_app/controller-concerns.md

I'm concerned about the lack of documentation about our controller concerns. :trollface: 
Seeing that there has been a lot of friction with how the `Authenticated` and `RequireKnownShop` controller concern compete with each other to determine the `current_shopify_domain` I felt it would be helpful to document the intents of these concerns so users can know how to best use them.
While I'm [still a fan of renaming these concerns](https://github.com/Shopify/shopify_app/issues/1502) to better match their behavior and intent, I think having docs to explain the intents behind concerns will be helpful even if we rename them in the future.
Ensure what I have documented matches the intent and functionality of the concerns.
Before submitting the PR, please consider if any of the following are …

add docs for public controller concerns

---

README.md

It's been over 6 years since Rails 5 was released, so I'd say this notice is no longer necessary.
Also I doubt the old gem version would be usable any more due to all the other changes that have happened.

Remove outdated Rails 4 note from README

---

CHANGELOG.md
app/controllers/concerns/shopify_app/require_known_shop.rb
lib/shopify_app/controller_concerns/login_protection.rb
test/controllers/concerns/require_known_shop_test.rb
test/dummy/app/controllers/application_controller.rb
test/dummy/app/controllers/home_controller.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Closes https://github.com/Shopify/first-party-library-planning/issues/486
`RequireKnownShop` and `LoginProtection` both have a method `current_shopify_domain` but with different implementations. If both these concerns are included, it can result in unintentional behaviour, since one method will overwrite the other.
1. 
2. 
3. 

Detect controller concern clash

---

CHANGELOG.md
README.md
app/controllers/concerns/shopify_app/ensure_authenticated_links.rb
app/controllers/shopify_app/callback_controller.rb
app/controllers/shopify_app/extension_verification_controller.rb
app/controllers/shopify_app/sessions_controller.rb
docs/shopify_app/logging.md
lib/generators/shopify_app/add_marketing_activity_extension/templates/marketing_activities_controller.rb
lib/generators/shopify_app/install/templates/shopify_app.rb.tt
lib/generators/shopify_app/rotate_shopify_token_job/templates/rotate_shopify_token_job.rb
lib/shopify_app.rb
lib/shopify_app/configuration.rb
lib/shopify_app/controller_concerns/ensure_billing.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/controller_concerns/redirect_for_embedded.rb
lib/shopify_app/controller_concerns/webhook_verification.rb
lib/shopify_app/logger.rb
lib/shopify_app/managers/webhooks_manager.rb
lib/shopify_app/session/jwt.rb
lib/shopify_app/session/session_repository.rb
test/controllers/concerns/ensure_authenticated_links_test.rb
test/shopify_app/session/jwt_test.rb
test/test_helper.rb

This is intended to add logs to critical areas of the code to ease the pain of debugging. 
closes https://github.com/Shopify/first-party-library-planning/issues/482
Read through all of the logs. If you are really cool you can test some logs out by using a testing app.
1. Does this PR follow our logging approach?
2. Read logging messages to makes sure they sound clear and make sense.
3. Should we add logs anywhere else?
4. Do the logs fall in the correct level?

Adding Debug Logs

---

CHANGELOG.md
lib/shopify_app/configuration.rb
test/shopify_app/configuration_test.rb

The gem currently provides two strategies for verifying user scopes:
* ShopifyApp::AccessScopes::NoopStrategy 
* ShopifyApp::AccessScopes::UserStrategy
Some apps (likely only first party apps made by Shopify) may have special requirements and need to use a different strategy. This PR adds a configuration option to allow that.
Reach out to me on Slack to discuss.
1. Is there any way this could break an existing app?

Add configuration option for user access scopes strategy

---

CHANGELOG.md
lib/shopify_app/access_scopes/noop_strategy.rb
lib/shopify_app/access_scopes/user_strategy.rb
lib/shopify_app/controller_concerns/login_protection.rb

There are two places that we check the user's scopes when determining if a re-auth is needed:
* `update_access_scopes?` in the access scopes user strategy.
* in `LoginProtection#activate_shopify_session` 
In #1599 we added an option to set the user strategy. But this has a gap, since only one of the above listed places is within the strategy. To have proper control over these checks, we need both of them to be in the strategy.
This PR aims to not alter any existing behaviour, it only moves code around.
1. 
2. 
3. 

Move covered scopes check into strategy

---

CHANGELOG.md
docs/Upgrading.md
lib/shopify_app/controller_concerns/login_protection.rb

`Itp`'s deprecation logs were getting sent when loading `LoginProtection`. 

Remove `Itp` from `LoginProtection`

---

CHANGELOG.md
lib/shopify_app/session/jwt.rb
test/shopify_app/session/jwt_test.rb

fixes: https://github.com/Shopify/shopify_app/issues/1567
We decided to remove this logged output. If we feel like we need it again we should consider putting it in a lower log level like `:debug` or `:info` so it would be easier for devs to turn off.
1. Do we like this approach?

Remove Logged output for rescued JWT exceptions 

---

.github/ISSUE_TEMPLATE/ENHANCEMENT.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Now that we provide better logging capabilities in the library package, we should encourage folks to increase log verboseness before opening an issue, so that we can get as much information as possible upfront.
This PR also tweaks the templates' general wording so they're simpler, and makes the comments actual comments so they don't show up in created issues.

Improve github templates

---

docs/shopify_app/engine.md
docs/shopify_app/session-repository.md

This removes all reference to the `omniauth.rb`. We aren't generating this file anymore so we should be safe to remove this documentation. We originally stopped generating `omniauth.rb` [here](https://github.com/Shopify/shopify_app/commit/6f1d779cfce7aec7e0b3a15b7ec64601aeec130b#diff-0c8ed94603ea781e0532daf48ed4389f23be762f6cbcc849ef7032ab8148fb89).
address: https://github.com/Shopify/shopify_app/issues/1541
1. I need to go through the steps in each of the docs I edited. If the docs work as expected we should be good to ship.

Remove `OmniAuth` from the Docs

---

CHANGELOG.md
Gemfile.lock
app/controllers/concerns/shopify_app/ensure_installed.rb
app/controllers/shopify_app/callback_controller.rb
lib/shopify_app.rb
lib/shopify_app/utils.rb
shopify_app.gemspec
test/shopify_app/utils_test.rb

1. Fixes bug where using a custom `myshopify_domain` with several subdomains would falsely classify the redirect as a phishing attack. This change replaces the regex with `Addressable::URI` which has far more support for all the variants of parsing a URI in ruby.
2. Adds some logging we forgot with previous PRs
- Should be able to customize `myshopify_domain` with a domain that includes several subdomains and install the app
- Should still be able to use default `myshopify.com` myshopify_domain and install the app

Allow a more complex customized `myshopify_domain`

---

CHANGELOG.md
lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

This skips the redirect-to-reauthenticate block in `LoginProtection` 
We had an incident earlier this week where we were doing a scope upgrade and despite us disabling [`reauth_on_access_scope_changes`](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/configuration.rb#L22) ahead of time.
The scopes were updated/backfilled on the Shopify Core side, but since the cached scopes in `user` and `shop` models were a subset of the actually-approved scopes in Core requests were rejected with a `401` response without even sending them to Core.
This was surprising behaviour to us since we'd disabled the feature intentionally ahead of time.
1. Have an existing set of scopes cached on the `user` and `shop` models
2. Add a new scope c (ie: in `config.scope`)
3. Set …

Don't redirect on mismatching scopes if configuration is disabled

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Bumps version to 21.4.1, which includes a bugfix for `reauth_on_access_scope_changes` (See https://github.com/Shopify/shopify_app/pull/1639)

Packaging for release 21.4.1

---

CHANGELOG.md
lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

Installs with the unified admin url were not working. This PR recognizes if a unified admin url was used and converts it to the old url format. This is a bandaid right now since core doesn't support the authorize routes with the new format. 
closes https://github.com/Shopify/shopify_app/issues/1660
Try to install an app using a unified admin store url.
1. Is `unified_admin?(uri)` a good way to determine if a url is unified admin?

Support Unified Admin

---

CHANGELOG.md
lib/generators/shopify_app/add_webhook/templates/webhook_job.rb.tt
lib/shopify_app/managers/webhooks_manager.rb
test/shopify_app/managers/webhooks_manager_test.rb

Fixes two bugs with webhooks within the app gem:
1. The webhook generators need to use the session that is now passed in the block when using `with_shopify_session`
2. `ShopifyApp::WebhhooksManager#recreate_webhooks!` was using API libraries methods to recreate webhooks instead of the methods it already had to do the same work. Since there were differing approaches with storing what topics were being used this was introducing bugs to consumers of both libraries. 
Should address https://github.com/Shopify/shopify-api-ruby/issues/1123 and https://github.com/Shopify/shopify_app/issues/1659
Use this branch with a shopify app created with the CLI. Create webhooks:
```
irb(main):003:0>  ShopifyApp::WebhooksManager.recreate_webhooks!(session:)
=> [{:topic=>"app/uninstalled", …
```

Refactor recreate webhooks logic

---

lib/shopify_app/session/session_repository.rb
test/dummy/config/initializers/shopify_app.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Removes the abstract session storage from the API library

eject session storage from session repository

---

README.md
docs/shopify_app/sessions.md

Clarify how sessions are loaded and what controller concerns should be used. Adds the missing initializer docs for shop/user session persistence.

Loading session docs

---

CHANGELOG.md
lib/shopify_app/session/in_memory_user_session_store.rb
test/shopify_app/session/in_memory_user_session_store_test.rb

Using `ShopifyApp` gem's `InMemoryUserSessionStore` doesn't work out of the box 
`shopify_user_id` does not belong in `ShopifyAPI::Auth::AssociatedUser` , using `id` instead.
Added test around `InMemoryUserSessionStore` as well.
Set configuration user session repository to use `InMemoryUserSessionStore`, see that it fails before this fix, and can store sessions after this fix.
```ruby
ShopifyApp.configure do |config|
#...
config.shop_session_repository = ShopifyApp::InMemoryShopSessionStore
config.user_session_repository= ShopifyApp::InMemoryUserSessionStore
#...
end
```

Fix InMemoryUserSessionStore - user.shopify_user_id does not exist

---

karma.conf.js
package.json
yarn.lock

Currently, we're getting some failures because karma is running an older version in our tests. This PR updates the dependency to unblock us.
Run the tests, both JS and Ruby!

Bump Karma to v6+

---

CHANGELOG.md

Simply fixing the style for the latest release. Missing the heading bar, making `21.8.1` quite small.

Fix CHANGELOG style for release 21.8.1

---

CHANGELOG.md
lib/generators/shopify_app/add_webhook/add_webhook_generator.rb

Fixes #1747
Please check if the webhook job is created under the correct directory.
1. Run `bundle add shopify_app`
2. Set `config.webhook_jobs_namespace = "shopify/webhooks"`
3. Run `bin/rails g shopify_app:add_webhook --topic carts/update --path webhooks/carts_update`
4. Check if `app/jobs/shopify/webhooks/carts_update_job.rb` is created

Fix `add_webhook` generator to create the webhook jobs under the correct directory

---

CHANGELOG.md
Gemfile.lock
shopify_app.gemspec

* Update shopify_api gem to [latest version](https://rubygems.org/gems/shopify_api/versions/13.4.0) 

Update shopify-api to v13.4.0

---

CHANGELOG.md
docs/shopify_app/sessions.md
lib/generators/shopify_app/user_model/templates/db/migrate/add_user_expires_at_column.erb
lib/generators/shopify_app/user_model/user_model_generator.rb
lib/shopify_app/configuration.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/session/user_session_storage_with_scopes.rb
test/generators/user_model_generator_test.rb
test/shopify_app/controller_concerns/login_protection_test.rb
test/shopify_app/session/user_session_storage_with_scopes_test.rb
test/support/session_store_strategy_test_helpers.rb
test/test_helper.rb

Embedded apps using user tokens currently have to wait for a 401 from Shopify to know that the user token is not valid anymore. By storing the token expiry date, we are able to detect an expired session without a round trip to Shopify and to trigger the Oauth flow to get a fresh token.
Goals of this PR are:
- to store the user token expiry date and to check it during the session check. This allows to trigger the Oauth flow early and has the nice side effect of removing useless calls to Shopify
- to align `shopify_app` with `shopify-app-js` which already stores the expiry date in the data model ([Prisma one](https://github.com/Shopify/shopify-app-js/blob/2dec481c10109ba4b16fc4f7c4ef30819361d06f/packages/shopify-app-session-storage-prisma/prisma/schema.prisma#L16) for example) and checks it …

Store session expiry and check it to trigger a re-auth

---

CHANGELOG.md
config/routes.rb

Fixes [Shopify Ruby Template , APP_UNINSTALLED Webhook Delivery Failed, Can't Verify CSRF Token.](https://github.com/Shopify/shopify-app-template-ruby/issues/115)
* This makes the `type` param on the webhooks route optional
* When webhooks are initiated from the CLI they are sent to the `/api/webhooks` address
* Prior to this change this was causing CLI initiated webhooks to error
* The webhook type is never read from the URL param, and always from the webhook header so we do not forsee any issues with making this param optional.
_Are there any cases where you forsee this being an error?_

Make type param optional on webhook route

---

docs/shopify_app/controller-concerns.md
lib/shopify_app/controller_concerns/embedded_app.rb
test/controllers/concerns/embedded_app_test.rb

> **TLDR:** The PR gives an app developer more granular control over what layout to render when using the `shopify_app` gem to build an embedded Shopify app.
When running a Shopify app in embedded mode, every controller that requires an authenticated session will use the embedded app layout by default. This is enforced by the `ShopifyApp::EmbeddedApp` module.
As a default, this is great. It helps the developer to make fewer choices when they start to develop their new Shopify app. However, sometimes one wants to run an embedded app in non-embedded mode.
Some examples of running a normally embedded app in non-embedded mode:
- When the remote environment is a CI;
- When the remote environment is a preview/PR app;
- When the developer wants to run the app in a non-embedded mode for testing. …

Allow more control over the application layout

---

CHANGELOG.md
lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

Related to #1708
After a 401 response from Shopify, we were simply attempting to redirect to Shopify, which wouldn't work for XHR requests for embedded apps.
We can instead use redirect_to_login, which is aware of the context and will return the appropriate response in all cases.
You can reproduce the problem by:
- installing an app
- stopping my server
- uninstalling the app
- restarting server
- opening app
Before, this would lead to an attempt at logging in within the iframe, which would fail.
Is there any reason _not_ to use the 401 response with headers at this point?

Properly handle 401 errors in XHR requests with LoginProtection

---

CHANGELOG.md
app/controllers/shopify_app/callback_controller.rb
test/controllers/callback_controller_test.rb

Fixes #1708
Currently, we use the session we just created in the OAuth callback to trigger webhook registration. When using online tokens, that registration might not kick in before the token has expired.
To solve that, we can register webhooks using offline tokens, which won't expire.
- Install an app in a store, but don't run the webhook manager job
- Alter the user access token in the database
- Perform the job
Before this change, that would break. Now, it should work the same way.
1. Does this have any impact on performance?
2. Is it enough?

Always register webhooks with offline sessions

---

app/controllers/shopify_app/callback_controller.rb

This adds a log at debug level to the callback rescue. It does not feel right to quietly rescue and redirect here.

add debug message to callback rescue

---

CHANGELOG.md
app/controllers/shopify_app/callback_controller.rb
docs/Upgrading.md
test/controllers/callback_controller_test.rb

In the unlikely scenerio  that users have customized the oauth flow and throw their own error class, we will no longer catch non-shopify API errors. 

No longer rescue non-shopify errors during OAuth

---

.github/ISSUE_TEMPLATE/bug-report.md

We want to be able to solve as many problems as possible, and help unblock developers. However, when we get duplicate / hard to reproduce issues, it takes away from the time we could be spending fixing them.
Revamping the issue template to suggest some things developers can check before opening an issue to see if a solution has been found, or to ensure we're getting as much context as we can, which really makes it easier for us to solve issues.

Improve issue template

---

CHANGELOG.md

We have a migration guide for v22, but it's currently not very easy to find from the changelog (which e.g. dependabot would reference). This PR simply adds a link there.
Does the link work?

Link to v22 migration guide in changelog

---

app/controllers/shopify_app/sessions_controller.rb
test/controllers/sessions_controller_test.rb

For issue:
- https://github.com/Shopify/develop-app-access/issues/143
Depends on issue: (not directly, but the redirects won't work properly unless we have token exchange)
- https://github.com/Shopify/shopify_app/pull/1817 
📹 [VIDEO DEMO](https://videobin.shopify.io/v/kGzWL4)
Redirect to Shopify managed install path during login instead of starting auth code OAuth flow.
- [ will update when token exchange feature is complete  ] Update `CHANGELOG.md` if the changes would impact users
- [ will update when token exchange feature is complete  ] Update `README.md`, if appropriate.
- [ will update when token exchange feature is complete  ] Update any relevant pages in `/docs`, if necessary

Redirect to shopify managed install path during login

---

CHANGELOG.md
Gemfile.lock
shopify_app.gemspec

Bump shopify_api to v14.1.0

---

app/controllers/concerns/shopify_app/ensure_installed.rb
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/layouts/app_bridge.html.erb
config/routes.rb
lib/shopify_app/controller_concerns/token_exchange.rb
test/controllers/sessions_controller_test.rb
test/dummy/config/initializers/shopify_app.rb
test/routes/sessions_routes_test.rb
test/shopify_app/controller_concerns/token_exchange_test.rb

- closes https://github.com/Shopify/develop-app-access/issues/145
- Handle invalid session token errors 
- Redirect to app-bridge-next bounce page if session token is invalid & Auth header doesn't exist
- Respond with 401 if auth header exists and session token is invalid. If the app's front-end is using CDN version of app bridge next, it'll automatically be retried. otherwise, the 401 error will be exposed.
* 📹 [Redirecting to bounce page on initial app render](https://videobin.shopify.io/v/5rOD2g) (we are not parsing `id_token` from URL param yet, so session token will be invalid initially, this redirect shouldn't be hit as often once we are using `id_token`)  
* For testing - I created a temp global variable count that raises an "invalid session token" error on **every other try**. 
* …

Handle invalid session token

---

CHANGELOG.md
Gemfile.lock
docs/Troubleshooting.md
docs/Upgrading.md
lib/shopify_app.rb
lib/shopify_app/auth/token_exchange.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/controller_concerns/token_exchange.rb
lib/shopify_app/controller_concerns/with_shopify_id_token.rb
lib/shopify_app/middleware/jwt_middleware.rb
lib/shopify_app/session/jwt.rb
shopify_app.gemspec
test/shopify_app/controller_concerns/login_protection_test.rb
test/shopify_app/controller_concerns/token_exchange_test.rb
test/shopify_app/controller_concerns/with_shopify_id_token_test.rb
test/shopify_app/middleware/jwt_middleware_test.rb
test/shopify_app/session/jwt_test.rb

- https://github.com/Shopify/develop-app-access/issues/289
* Bumps `shopify_api` to `14.3.0`
* Support `id_token` from URL param 
* Extracted controller concern `WithShopifyIdToken`
* This concern provides a method `shopify_id_token` to retrieve the Shopify Id token from either the authorization header or the URL param `id_token`.
* `ShopifyApp::JWTMiddleware` supports retrieving session token from URL param `id_token`
* `ShopifyApp::JWTMiddleware` returns early if the app is not embedded to avoid unnecessary JWT verification
* `LoginProtection` now uses `WithShopifyIdToken` concern to retrieve the Shopify Id token, thus accepting the session token from the URL param `id_token`
* Marking `ShopifyApp::JWT` to be deprecated in version 23.0.0, use `ShopifyAPI::Auth::JwtPayload` instead.
- …

Support id_token from URL params

---

CHANGELOG.md
app/controllers/concerns/shopify_app/ensure_installed.rb
lib/shopify_app/controller_concerns/embedded_app.rb
lib/shopify_app/controller_concerns/ensure_billing.rb
lib/shopify_app/controller_concerns/login_protection.rb
lib/shopify_app/controller_concerns/redirect_for_embedded.rb
lib/shopify_app/controller_concerns/token_exchange.rb
lib/shopify_app/controller_concerns/with_shopify_id_token.rb
test/controllers/concerns/embedded_app_test.rb
test/controllers/concerns/ensure_billing_test.rb
test/shopify_app/controller_concerns/token_exchange_test.rb
test/shopify_app/controller_concerns/with_shopify_id_token_test.rb

- Fixes: https://github.com/Shopify/develop-app-access/issues/295
* Making sure EnsureBilling and EnsureAuthenticatedLinks can call methods defined in token exchange, by extracting some common helper methods for re-use
* Fixed an infinite redirect loop caused by handling billing API error -
* Steps to reprduce:
1. Open app
2. EnsureHasSession checks if billing is valid
3. Billing API responds with billing error 
4. EnsureBilling handles billing error by redirecting to shop /login with shop and host params
5. /login starts auth again
6. Auth CallbackController handles the callback, but it also checks billing, which could still return error - thus redirecting back to /login again.  ↺
* Fix was to only redirect to shop /login withOUT shop and host params so that /login does not re-start …

EnsureBilling and EnsureAuthenticatedLinks works with token exchange

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Package v22.2.1
* Patch - Don't delete session on 401 errors during retry in `with_token_refetch` [#1844](https://github.com/Shopify/shopify_app/pull/1844)

Packaging for release 22.2.1

---

lib/generators/shopify_app/install/templates/shopify_app.rb.tt

What this PR does
This PR fixes the ENV check to correctly pass in a boolean for the `test:` value on `BillingConfiguration` rather than a string. **Note**: This only changes the template generated, not the underlying BillingConfiguration code itself.
Reviewer's guide to testing
Currently, if present, the environment variable will be pulled in as a string i.e. "true" / "false". That will fail when creating the recurring charge with the following error:
```[{"message"=>"Variable $test of type Boolean was provided invalid value",
"locations"=>[{"line"=>6, "column"=>3}], "extensions"=>{"value"=>"true", "problems"=>[{"path"=>[], "explanation"=>"Could not coerce value
\"true\" to Boolean"}]}}]
```
This fixes a bug introduced in my original pr here: #1688 
Things to focus on
N/A
Checklist …

Fixing SHOPIFY_TEST_CHARGES env var check in template

---

CHANGELOG.md
lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

* When `javascript:alert(1)` is used the `host` is `nil` not empty
* This was causing the code to crash in `unified_admin` where we would attempt to split `uri.host`

[Fix] Update sanitize_shop_domain to handle nil host

---

CHANGELOG.md

Fixes up the changelog. Noticed it looking a bit off.
**Before**
**After**

Fix changelog style for 22.2.1 and unreleased

---

lib/shopify_app/controller_concerns/login_protection.rb

Apps which use cookies for session storage, and thus have a 4kB session data limit, may choose to override this method to prevent excessively-long `query` strings from causing a CookieOverflow error.
Currently, apps must override the entire `redirect_to_login` method. To make gem updates easier, we want to override a smaller area.
This PR does not change functionality.
Confirm that the method extraction was performed correctly, ie. without changing functionality.
Please let me know if any of the following are necessary in this case. It's not immediately clear to me if they are necessary.

LoginProtection: Extract private method set_session_return_to

---

CHANGELOG.md
app/assets/images/storage_access.svg
config/locales/cs.yml
config/locales/da.yml
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fi.yml
config/locales/fr.yml
config/locales/it.yml
config/locales/ja.yml
config/locales/ko.yml
config/locales/nb.yml
config/locales/nl.yml
config/locales/pl.yml
config/locales/pt-BR.yml
config/locales/pt-PT.yml
config/locales/sv.yml
config/locales/th.yml
config/locales/tr.yml
config/locales/vi.yml
config/locales/zh-CN.yml
config/locales/zh-TW.yml
karma.conf.js
lib/shopify_app/engine.rb

This PR is a cleanup to:
1. Remove non-existent references to JS files from the Rails precompile.
"shopify_app/post_redirect.js",
"shopify_app/top_level.js",
"shopify_app/enable_cookies.js",
"shopify_app/request_storage_access.js",
"storage_access.svg",
1. Remove the `storage_access.svg`
1. Remove unused translation keys for features that have been removed.
Most of this is related to old features such as cookies (https://github.com/Shopify/shopify_app/pull/617), which was removed in https://github.com/Shopify/shopify_app/pull/1611 (2 years ago).

Remove references to unused assets and features

---

CHANGELOG.md
lib/shopify_app/controller_concerns/token_exchange.rb

Fixes #1866
When app root URL is opened directly outside of iframe it used to redirect to `/login` page. With Token Exchange auth it now throws an exception `ShopifyAPI::Errors::MissingJwtTokenError` because `current_shopify_domain` method is called by `ShopifyApp::FrameAncestors` and it doesn't have any error handling at the moment.
In this PR I added missing error handling for `current_shopify_domain` and redirect to `/login` work again.
https://github.com/Shopify/shopify_app/assets/839922/da1eb29c-1f7f-4f26-b8ea-637778cfd8b0
To reproduce the issue:
1. Launch the app that uses Token Exchange auth
2. Open root URL outside of iframe
3. You should see `ShopifyAPI::Errors::MissingJwtTokenError`

Add invalid id token handling for `current_shopify_domain` method

---

CHANGELOG.md
lib/shopify_app/controller_concerns/embedded_app.rb
test/controllers/concerns/embedded_app_test.rb
test/shopify_app/controller_concerns/token_exchange_test.rb

Fixes deep link behavior to make sure the original path and params are preserved after redirect to app embed. Right now all deep links are redirected to home page. In addition to deep links it fixes opening links in new tab in app embed.
https://github.com/Shopify/shopify_app/assets/839922/a1c43f6a-8486-40ea-af4c-5ef384906807

Keep original path and params when redirecting deep links to embed

---

CHANGELOG.md
app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

Closes: https://github.com/Shopify/develop-app-runtime-primitives/issues/396
Fixes the install path for SPIN URLs
https://videobin.shopify.io/v/5ZGq8n
https://videobin.shopify.io/v/oadmV1

Fix unified admin install path for spin

---

CHANGELOG.md
lib/shopify_app/controller_concerns/localization.rb
test/shopify_app/controller_concerns/localization_test.rb

The changes in https://github.com/Shopify/shopify_app/pull/1711 introduced a bug where single-page apps that don't include the locale param in subsequent requests were unable to properly set the locale that was persisted in the user session. Instead they would use the default locale.
See https://github.com/Shopify/shopify_app/pull/1711/files#r1664570299 for background.
Nothing in particular since this is a very small change. A new test case was added to make sure it was accounted for.

Fix bug where locale is not read from session

---

docs/shopify_app/sessions.md

Following up Shopify/shopify-app-template-ruby#136, the ruby template will ship with the user model and migrations already present in the codebase. This means that running the generator is no longer needed to enable User session persistence.
This change might impact users who started the template with the previous version of the ruby template. In that case, this documentation won't work, as they need to also run the generator.

Update session persistence documentation for ruby template

---

docs/Quickstart.md

* Flash messages do not work with the frontend template
* You need to allow 3rd party cookies to save the flash messages to the session.
* Fixes #1796

Clarify flash messages documenation

---

CHANGELOG.md
lib/shopify_app/test_helpers/shopify_session_helper.rb

Fixes this issue:
- https://github.com/Shopify/shopify_app/issues/1867
We were missing a test stub for token exchange because we introduced a new helper in `ShopifyAPI::Utils::SessionUtils` for [session_id_from_shopify_id_token](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/utils/session_utils.rb#L45), used in [Token Exchange](https://github.com/Shopify/shopify_app/blob/fb4dd79a3c64ea5495cb15969bdb7c70e9a2e7b9/lib/shopify_app/controller_concerns/token_exchange.rb#L43) 

Add test stub for token exchange auth

---

docs/shopify_app/webhooks.md

There are more reasons to use shop-specific webhooks than I realised.  Instead of listing them all, I've updated the docs to link to the shopify.dev docs that explain the reasons
- ~~[ ] Update `CHANGELOG.md` if the changes would impact users~~
- ~~[ ] Update `README.md`, if appropriate.~~
- ~~[ ] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.~~

Soften the app-specific webhook docs

---

CHANGELOG.md
Gemfile.lock
docs/shopify_app/webhooks.md
lib/shopify_app/managers/webhooks_manager.rb
shopify_app.gemspec
test/shopify_app/managers/webhooks_manager_test.rb

To support passing a filter to webhook registrations, the filter parameter is needed.
Depends on https://github.com/Shopify/shopify-api-ruby/pull/1347
```ruby
gem "shopify_api", github: 'nebulab/shopify-api-ruby', branch: 'kennyadsl/add-filter-support'
gem "shopify_app", github: 'nebulab/shopify_app', branch: 'kennyadsl/add-filter-support'
```
The following registration won't work without the changes in the two PRs above, because apparently, to register a metaobject-related webhook, at least one filter needs to be specified.
```ruby
ShopifyApp.configure do |config|
config.webhooks = [
{
topic: "metaobjects/update",
path: "api/webhooks/metaobjects_update",
filter: "type:my_type OR type:my_other_type",
},
]
end
```
Before submitting the PR, please consider if any of the following are …

Add support for filters in webhook registration

---

lib/shopify_app/configuration.rb

We've seen this console warning for 8 months with each app boot in dev, thinking we could remove the warning. 
Especially since if there's breaking changes they are could be raised in the changelog + via exceptions.

Drop log_v23_deprecations console warning

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/utils.rb
lib/shopify_app/version.rb
test/shopify_app/utils_test.rb

In this PR we add a new hostname `.shop.dev` to Shopify trusted domains to prevent internal flows from treating this hostname as a potential phishing attack.
- Install a Shopify App, such as Shop channel locally. Requests referred from the Admin should not be treated as phishing and be nullified.
```
[ ShopifyApp | INFO | Shop Not Found ] host param from callback is not from a trusted domain
[ ShopifyApp | INFO | Shop Not Found ] redirecting to root as this is likely a phishing attack
```

Add support for trusted Shopify domain .shop.dev

---

.github/workflows/build.yml
CHANGELOG.md
docs/Upgrading.md
shopify_app.gemspec

* Ruby 3.0 is EOL
* We need to drop support of ruby 3 to resolve dependencies
* See #1958 
1. 
2. 
3. 

[Breaking] Drops support for Ruby version 3.0
