lib/shopify_app.rb
lib/shopify_app/sessions_controller.rb
lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

in Qbo we use the sanitize function outside of the SessionsController so in order to make the best use of this new gem configuration I am moving this function into a utils module which can more easily be used in other places.
@stephenminded @shawnfrench

add utils module

---

lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
test/generators/install_generator_test.rb

This PR moves all the defaults into one place so it is super clear. Also fixes a bug with how the embedded flag was set.
for review:
@clayton-shopify @christhomson

Fix embedded flag

---

app/views/sessions/new.html.erb

Correct incorrectly spelled HTML tag: 'button'

---

lib/shopify_app/sessions_controller.rb

Fixes #134 (I'm 99% sure)
Fixes a session glitch where another return_to URL would be stored from a previous request by the same browser
cc @kevinhughes27

Fix session glitch

---

README.md

Added a comma on line 71: After running the `install` generator, you can start...
Also changed 'create' to 'creates' on line 81: It also creates a model called...

fixed typos in README file on line 71 and 80

---

README.md
lib/generators/shopify_app/install/install_generator.rb
test/generators/install_generator_test.rb

I am updating the generator to put a default redirect uri of local host.
cc @ShayneP

add a default redirect uri

---

README.md

Realized that we should add these notes while creating a new app the other day with @christinejordan 
for review
@ShayneP

readme updates for creating a new app in the partners area

---

QUICKSTART.md
README.md

Added a few notes! cc @ShayneP @gavinballard

Add quickstart

---

app/views/sessions/new.html.erb

This simply add a bit of CSS to the default installation page. I'm no designer, so feel free to question my CSS.
Before:
After:
@kevinhughes27

Nicer installation page

---

QUICKSTART.md

Fix typo in QUICKSTART.md

---

lib/shopify_app/sessions_controller.rb

Fixes #195 
@kevinhughes27 @christianblais could you please review?

Use named routes in SessionsController, fixes #195

---

test/support/generator_test_helpers.rb
test/test_helper.rb

@kevinhughes27 @nwtn 
This will help me test generators in another gem

Change class monkeypatch to module monkeypatch

---

lib/generators/shopify_app/install/templates/embedded_app.html.erb

set forceredirect to true

---

example/Gemfile
example/app/controllers/authenticated_controller.rb
example/app/controllers/home_controller.rb
example/app/controllers/sessions_controller.rb
example/app/helpers/application_helper.rb
example/config/routes.rb
lib/shopify_app/version.rb

This updates the example app for the v7 namespace changes (#223 moved all the controllers into a namespace)
for review:
@nwtn @christinejordan

update example for v7

---

QUICKSTART.md

some heroku commands are not working while generating the app. so i thought it would be a good idea to update them along with how we add `shopify_app` gem to `Gemfile`

Changes to heroku commands in Quickstart.md

---

config/locales/en.yml
config/locales/es.yml
lib/shopify_app/sessions_concern.rb
lib/shopify_app/version.rb
test/controllers/sessions_controller_test.rb

It adds translations for "Logged In" in English and Spanish.
Could you guys have a look at it? @sbfaulkner @mattvleming

Add translation for flash messages

---

CHANGELOG

Adds an entry for v7.0.1 to CHANGELOG

Update CHANGELOG to 7.0.1

---

example/db/migrate/20160212213112_create_shops.rb

@kevinhughes27  @pseudomuto 
Adding `limit` and `null: false` for the timestamp and updating to use Rails `change` method for migration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shopify/shopify_app/259)

updating shop migration to use new rails pattern and adding limits and null falses

---

lib/generators/shopify_app/shop_model/shop_model_generator.rb
lib/generators/shopify_app/shop_model/templates/db/migrate/create_shops.rb
lib/generators/shopify_app/shop_model/templates/shop_helper.rb
test/app_templates/app/controllers/shopify_app/authenticated_controller.rb
test/generators/shop_model_generator_test.rb
test/support/generator_test_helpers.rb

Reverts Shopify/shopify_app#184
@gmalette @kevinhughes27

Revert "Create shop helper with shop model generation"

---

README.md

Ref #268 This is not clear currently without doing a code review!

Clarify project scope

---

lib/generators/shopify_app/add_webhook/add_webhook_generator.rb

@karlhungus @kevinhughes27. I have _no_ idea how to test this because we don't have a `test_framework` generator. I manually 🎩 in script-editor where we do have the generator.

Add hooks for tests in job

---

CHANGELOG
lib/shopify_app/login_protection.rb
test/controllers/sessions_controller_test.rb

Local tests are passing, need to 🎩

Removing http-equiv meta tags

---

CHANGELOG
lib/shopify_app/version.rb

@kevinhughes27 @nwtn @Hammadk I'm bumping the version here. Are there any other places I need to consider?

Bumping version

---

README.md

- Made the routes that get created more explicit
- added a root example, prompted by #286

Update App Proxy usage in README.md

---

CHANGELOG
lib/shopify_app/configuration.rb
lib/shopify_app/scripttags_manager_job.rb
lib/shopify_app/webhooks_manager_job.rb
test/shopify_app/configuration_test.rb

- will add spec when I get confirmation that we consider adding this feature

add ability to customise queue names

---

README.md

Add svg badge from [shields.io](http://shields.io/) to visually denote latest gem version.

Add gem-version badge to README

---

lib/generators/shopify_app/install/templates/embedded_app.html.erb

to get around data-turbolinks-track issue.
resolves #289

Move application.js to inside head

---

CHANGELOG.md

Format Changelog with Markdown
- changelog renamed to changelog.md
- edit changelog.md

Format Changelog with Markdown

---

lib/shopify_app/configuration.rb
test/shopify_app/configuration_test.rb

https://github.com/Shopify/shopify_app/pull/298

do not override active_job queue_name in initializer

---

index.md

update quickstart href from *.md -> *.html

update quickstart href from *.md -> *.html

---

lib/generators/shopify_app/home_controller/templates/home_controller.rb

Tiny change, to keep the 👮  happy.
/review @kevinhughes27 @alexcoco please

Comply with Policial

---

README.md

Added a section describing how to filter webhook data when configuring webhooks.
@kevinhughes27

Updated readme to include webhook filtering

---

lib/shopify_app/login_protection.rb

This PR removes code that's not used (and should have been removed in a previous PR).

Remove unused code form LoginProtection

---

lib/shopify_app/version.rb

Bump version to 7.2.3

---

config/locales/fr.yml

Added french translation used by i18n in locales. 
Let me know if there is anything else I can do.

Add french locales for i18n

---

CHANGELOG.md
lib/shopify_app/version.rb

This PR updates just packages this gem for a [minor version bump](https://github.com/Shopify/shopify_app/blob/master/RELEASING)

Packaging for release 7.2.5

---

.travis.yml
CHANGELOG.md
Gemfile.rails40
Gemfile.rails50
Gemfile.ruby22
Gemfile.ruby22.rails50
example/config/application.rb
lib/shopify_app/version.rb
shopify_app.gemspec
test/app_templates/config/application.rb
test/dummy/config/application.rb

Closes https://github.com/Shopify/shopify_app/issues/407

Packaging for release 7.2.7

---

CHANGELOG.md
lib/shopify_app/version.rb

* Add i18n locale param support [[#409]](https://github.com/Shopify/shopify_app/pull/409)

Packaging for release 7.2.7 

---

CHANGELOG.md
lib/shopify_app/version.rb

Package for release 7.2.9

---

CHANGELOG.md
RELEASING
lib/shopify_app/version.rb

This PR also simplifies `Releasing.md`.

Package for release 7.2.11

---

CHANGELOG.md
lib/shopify_app/version.rb

As per comment in https://github.com/Shopify/shopify_app/pull/433#issuecomment-315450149 bumping to 7.3.0

Package for release 7.3.0

---

README.md

This updates the documents for nested mounting and include a non-obvious change to the omniauth initializer that is required to make this work.
review
@Hammadk @EiNSTeiN-

Update docs for nested mounting

---

CHANGELOG.md
README.md
app/controllers/shopify_app/sessions_controller.rb
shopify_app.gemspec
test/controllers/sessions_controller_test.rb

code extraction from #457
cc @Hammadk @EiNSTeiN-

basic setup for per-user authentication

---

CHANGELOG.md
app/controllers/shopify_app/sessions_controller.rb
example/config/initializers/omniauth.rb
lib/generators/shopify_app/install/templates/shopify_provider.rb
test/controllers/sessions_controller_test.rb

extracted from #457
@Hammadk @EiNSTeiN-

Pass shop in the session

---

CHANGELOG.md
lib/shopify_app/version.rb

Packaging for release 8.2.0 which contains the following changes:
8.2.0
-----
* Add `webhook_jobs_namespace` config option. [[#463]](https://github.com/Shopify/shopify_app/pull/463)
* Updates login page styles to match the [Polaris](https://polaris.shopify.com/) design system. [[#474]](https://github.com/Shopify/shopify_app/pull/474)

Packaging for release 8.2.0

---

lib/shopify_app/utils.rb
test/shopify_app/utils_test.rb

Add stricter myshopify domain validation from https://github.com/Shopify/partners/pull/5426 / https://github.com/Shopify/partners/issues/2245

Stricter myshopify domain validation

---

README.md
app/controllers/shopify_app/webhooks_controller.rb

Updated README example for custom webhook controller to more closely match how `webhooks_controller.rb` works.

Adjustment to README on Custom Webhooks section

---

README.md

closes #510
cc @jamiemtdwyer @ShayneP

update README to reflect changes to concern names

---

shopify_app.gemspec

closes #493 #465
@ShayneP @jamiemtdwyer

bump minimum ruby version

---

app/controllers/shopify_app/sessions_controller.rb

Remove 'X-Frame-Options' on 'sessions#create'

---

README.md

Planning to make sure the Quickstart is still accurate next week. For now we'll reference the current video.
@jamiemtdwyer

Update App In 5 reference link to facilitate new video

---

README.md

AuthenticatedController inherits from ActionController::Base

Fix: AuthenticatedController inheritance docs

---

example/Gemfile

Fixed bundle install for example app

---

docs/Quickstart.md

Finishes #224 and resolves MD snippet nitpicks on Quickstart.md
CC @jamiemtdwyer for 👀

Quickstart.md: Update snippet MD to shell syntax, add notes on credentials to step 5

---

lib/shopify_app/controller_concerns/login_protection.rb
test/shopify_app/controller_concerns/login_protection_test.rb

We're currently seeing an issue where if we leave off the `.myshopify.com` bit of the shop query parameter we end up with the following error after a few redirects:
Example: `https://www.myapp.com/shopify_app/login?shop=shop1`
This PR uses adds a new `sanitized_params` that uses the `sanitize_shop_param` to make sure that the `sanitized_params[:shop]` is correct and contains the appropriate shopify domain.
cc/ @TejasM

Sanitizes the shop query param in case it's missing the .myshopify.com

---

CHANGELOG.md
lib/shopify_app/version.rb

I think I merge this in and then deploy via shipit, is that right?

Packaging for release 8.3.0

---

CHANGELOG.md
lib/shopify_app/version.rb

Release of `v8.3.1` which adds the ability to customize the login URL through the initializer.

Packaging for release 8.3.1

---

config/locales/de.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/it.yml
config/locales/ja.yml
config/locales/pt-BR.yml

This PR adds translations to the project. It will append multiple commits. Feel free to merge anytime.
Questions about the format of this PR? Hop in the `#intl-services` Slack channel.
Questions about the translations of this PR? Hop in the `#translation` Slack channel.
We're happy to help!
@Shopify/translation-platform

Add translations: merchant

---

CHANGELOG.md
README.md
example/config/initializers/shopify_app.rb
lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/shopify_app.rb
lib/shopify_app/version.rb
test/generators/install_generator_test.rb

Didn't follow the release practices at first. Fixing in this PR.
Original PR: #629

Packaging for release 8.3.2

---

CHANGELOG.md
lib/shopify_app/version.rb

Packaging for release 8.4.0

---

example/app/assets/javascripts/modals.js
example/app/views/home/breadcrumbs.html.erb
example/app/views/home/form_page.html.erb
example/app/views/home/index.html.erb
example/app/views/home/pagination.html.erb

Do not include examples of unsupported features

chore: remove unsupported legacy EASDK examples

---

CHANGELOG.md
docs/Releasing.md
lib/shopify_app/version.rb
package.json

Packaging for release 8.4.1

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Creating release for `8.4.2`
cc/ @Shopify/platform-dev-tools-education

Packaging for release 8.4.2

---

CHANGELOG.md
lib/shopify_app/version.rb

Packaging for version 8.5.0 release.
> 8.5.0
> -----
> Added support for rotating Shopify access tokens:
> 
> * Added a generator shopify_app:rotate_shopify_token_job for generating the job to perform token rotation
> * Extend Shopify app configuration to support a new and old secret token
> * Extended webhook validation code to support validating against new and old secret tokens
> * See the README for more details: https://github.com/Shopify/shopify_app#rotateshopifytokenjob

Packaging for release 8.5.0

---

CHANGELOG.md
lib/generators/shopify_app/rotate_shopify_token_job/templates/rotate_shopify_token_job.rb
lib/shopify_app/version.rb

Fix typo in job & release 8.5.1

---

app/assets/javascripts/shopify_app/partition_cookies.js
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/enable_cookies.html.erb

This provisionally fixes #701. I've tophatted it on a local app, but I'm struggling with how I'd test this (and it makes me super uncomfortable there's no tests).
Open to feedback!

Fix the request by adding the missing params

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging up for 8.6.1 release.

---

CHANGELOG.md
Gemfile
README.md
lib/shopify_app/version.rb
package.json

Setting up for version 9.0.0 release.
Docs and change log update.

Package for 9.0.0

---

lib/generators/shopify_app/add_after_authenticate_job/add_after_authenticate_job_generator.rb

fix after_authneticate_job typo

---

translation.yml

For any questions, contact #intl-services.
Owners: @Shopify/platform-dev-tools-education

Update configuration languages in translations.yml

---

CHANGELOG.md
lib/shopify_app/version.rb
package-lock.json
package.json

^ don’t merge/release until we confirm this

Packaging for release 9.0.2

---

app/views/shopify_app/sessions/enable_cookies.html.erb
app/views/shopify_app/sessions/request_storage_access.html.erb
app/views/shopify_app/sessions/top_level_interaction.html.erb
app/views/shopify_app/shared/redirect.html.erb

see #734 
i’m going to need some help 🎩 this since i’m not super familiar with what all the states in the flow are supposed to look like.

add meta viewport to fix responsive problems in ITP flow

---

CHANGELOG.md
lib/shopify_app/version.rb
package-lock.json
package.json

Closes https://github.com/Shopify/shopify_app/pull/772
Follow-up to https://github.com/Shopify/shopify_app/pull/771
Unblocks https://github.com/Shopify/shopify/pull/203904
👋 @nwtn Are all other undeployed changes in master, now targeting 10.0.0 ready for release? Any other release notes to add?

Packaging for release 10.0.0

---

lib/generators/shopify_app/install/install_generator.rb
lib/generators/shopify_app/install/templates/user_agent.rb

this appends a ShopifyApp string to the user agent that ShopifyApi provides

add a custom user agent to generated apps

---

config/locales/pt-BR.yml

This PR adds translations to the project. It will append multiple commits. Feel free to merge anytime.
Questions about the format of this Pull Request? Hop in the [#intl-services](https://shopify.slack.com/messages/C7TJQLVC7) Slack channel.
Questions about the translations in this Pull Request? Hop in the [#translation](https://shopify.slack.com/messages/C3XPBC62U) Slack channel.
We're happy to help!
@Shopify/platform-dev-tools-education

Update translations: merchant

---

package.json

Pubish new version

---

CHANGELOG.md
package-lock.json
package.json

This project is not an installable node package so we should not need to bother with keeping the version in package.json up to date. We only use that file to install dependencies for tests.

remove version key from package.json

---

CHANGELOG.md
lib/shopify_app/version.rb

release 11.3.0

---

.travis.yml

I *think* this will resolve our CI problems

Trying to fix our CI builds

---

package-lock.json
package.json
yarn.lock

This should clear up our security warning on this repo

Fixing serialize-javascript security warning

---

README.md

Add readme instructions for the marketing activities extension generator

---

CHANGELOG.md
README.md

Addresses https://github.com/Shopify/shopify_app/issues/857

User-token documentation updates

---

README.md
docs/Quickstart.md

Hot on the heels of #854, I've done a more in-depth pass over both `readme` and `quickstart` to help provide clarity/assumed context for newer developers using this guide for the first time (particularly those that may not have the required pre-requisites on their machine or may not have a Heroku account). 
CCing the same Shopify folks from #854 since they have context already. :)

Copy improvements for readme and Quickstart

---

app/assets/javascripts/shopify_app/itp_helper.js
app/assets/javascripts/shopify_app/storage_access.js
test/javascripts/shopify_app/storage_access_test.js

fixes #881 
It seems like we missed a cookie while adding in the samesite fixes. I added this, however I am still getting warnings in my console about samesite cookies after this so there are other cookie that we need to find I think

Set Samesite=None on storage access cookie

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Update version 12.0.2

---

CHANGELOG.md
lib/shopify_app/version.rb

Packaging for release 12.0.3

---

app/assets/javascripts/shopify_app/storage_access.js
app/controllers/shopify_app/sessions_controller.rb
app/views/shopify_app/sessions/enable_cookies.html.erb
app/views/shopify_app/sessions/request_storage_access.html.erb
lib/shopify_app/controller_concerns/login_protection.rb
test/javascripts/shopify_app/storage_access_test.js

Reverts Shopify/shopify_app#895
This PR will be used to address the reason for revert, and original issue.
cc @joshreeves @tanema

Revert "Revert "Fix return_to address in Safari after enable_cookies and grated_storage_access""

---

CHANGELOG.md
README.md

Add missing documentation, including a slightly more expanded explanation of what happens when the callback is handled and a link to the changelog from the readme.
This closes #754.

Adding documentation about CallbackController and how to upgrade to 8.4.0 or newer

---

CHANGELOG.md
lib/shopify_app/version.rb

Packaging for release 12.0.6

---

CHANGELOG.md
README.md
lib/shopify_app/version.rb
package-lock.json
package.json
shopify_app.gemspec

This adds a migration guide, adds to the change log an updates the version
fixes #883
fixes #569
fixes #618

Updating to version 13

---

README.md

Updating 13.0.0 migration docs to highlight changes in `session[:shopify]`

Update changes to session

---

README.md
lib/shopify_app/test_helpers/all.rb
lib/shopify_app/test_helpers/webhook_verification_helper.rb

A webhook_verification_helper to run from your app

---

lib/shopify_app/session/jwt.rb
test/shopify_app/session/jwt_test.rb

When the JWT fails to validate, we should log to Rails log to make it easy to understand why. It's been difficult for us to debug without this logging.

Log JWT validation failures

---

README.md

Fix some typos and punctuation in the readme

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

13.2.0
------
* Get current shop domain from JWT header
* Validate that the omniauth data matches the JWT data
* Persist the token information to the session store

Packaging for release 13.2.0

---

README.md

My editor highlights unrecognized words, so these stood out while I was reviewing the README.

Some minor spelling and capitalization corrections

---

README.md

Remove redundant install line from README

---

CHANGELOG.md

Update changelog for #926

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

13.3.0
------
* Added Payload Verification module [#992](https://github.com/Shopify/shopify_app/pull/992)
* Add concern to check for valid shop domains in the unauthenticated controller

Packaging for release 13.3.0

---

.travis.yml
shopify_app.gemspec

Remove rvm 2.4 from Travis

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 14.1.0

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 14.2.0

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 14.3.0

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 14.4.0

---

app/controllers/shopify_app/sessions_controller.rb

Adding debug logs to sessions controller. We are trying to debug an issue with authentication in POS Channel and need additional logs to do so. See: #1073
Version update will be done in a separate PR. 

Adding debug logs to sessions controller

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 14.4.2

---

CHANGELOG.md
docs/Releasing.md
lib/shopify_app/version.rb
package.json

Shipping a small change for logging job paramters

Packaging for 14.4.4

---

CHANGELOG.md
lib/shopify_app/version.rb
package.json

Packaging for release 15.0.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Update all `html.erb` and `css` files to correspond with updated store admin design language [#1102](https://github.com/Shopify/shopify_app/pull/1102)

Packaging for release 16.0.0

---

lib/generators/shopify_app/home_controller/home_controller_generator.rb

Update conditional logic in home controller generator

---

docs/Releasing.md

(doesn't affect gem but needed for GitHub Actions CI)

Add `bundle` step to release notes

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

* Use Session Token auth strategy by default for new embedded apps #1111
* Create optional `EnsureAuthenticatedLinks` concern to authenticate deep links using Turbolinks #1118

Packaging for release 16.1.0

---

app/controllers/shopify_app/callback_controller.rb
app/controllers/shopify_app/sessions_controller.rb
lib/shopify_app/controller_concerns/itp.rb
lib/shopify_app/controller_concerns/login_protection.rb

Removing previously added debug logs as they're no longer needed.

Remove debug logs since they're no longer needed.

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Packaging for release 17.0.0

---

.github/workflows/release.yml
docs/Releasing.md

Closes https://github.com/Shopify/shopify_app/issues/1137
Don't believe this is testable locally.

Create release workflow;

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Packaging for release 17.0.1

---

README.md

Remove ForwardHQ as its been shutdown

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

17.1.0 (March 5, 2021)
----------
* Add warning to OmniAuth generator if shopify_provider exists to signal updates to OmniAuth configuration [#1188](https://github.com/Shopify/shopify_app/pull/1188)
* Create OmniAuthConfiguration object to build future OmniAuth strategies [#1190](https://github.com/Shopify/shopify_app/pull/1190)
* Add access scopes to Shop and User model generators [#1191](https://github.com/Shopify/shopify_app/pull/1191)
* Store access scopes after successful OAuth with ShopSessionStorageWithScopes and UserSessionStorageWithScopes [#1192](https://github.com/Shopify/shopify_app/pull/1192)
* Use access scopes strategies to handle changes to scopes requested by app [#1197](https://github.com/Shopify/shopify_app/pull/1197)
Before submitting the PR, please consider if any of …

Packaging for release 17.1.0

---

docs/Troubleshooting.md

This PR adds the following things to `/docs/Troubleshooting.md`:
* A table of contents
* A section on debugging common JWT session tokens issues
The best way to test this would be to view this file on the branch: https://github.com/Shopify/shopify_app/blob/update-troubleshooting-guide/docs/Troubleshooting.md
1. Are the links all working?
2. Is the information correct?

Add a session tokens section to Troubleshooting guide

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Packaging for release 17.2.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

18.0.0 (May 3, 2021)
----------
* Support OmniAuth 2.x 
* If your app has custom OmniAuth configuration, please refer to the [OmniAuth 2.0 upgrade guide](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0).
* Support App Bridge version 2.x in the Embedded App layout. [#1241](https://github.com/Shopify/shopify_app/pull/1241)

Packaging for release 18.0.0

---

service.yml

Updates the slack channel for the shopify_app.
Does the slack channel in service.yml look correct?
service.yml

updated service yml to point to new slack channel

---

README.md

This PR simply adds a bit of text and a link to apply to work at Shopify to the top of the README.

added job link to readme

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

18.0.2 (Jun 15, 2021)
----------
* Added careers link to readme. [#1274](https://github.com/Shopify/shopify_app/pull/12274)

Packaging for release 18.0.2

---

docs/Upgrading.md

Is this the appropriate level of detail for why upgrading to 18.1.1 is important?
Do we need to include any additional details on changes made between 17.2.0?

Adding upgrade notes for moving to v18.1.1

---

Rakefile
test/shopify_app/managers/scripttags_manager_test.rb
test/shopify_app/managers/webhooks_manager_test.rb

Uncomments tests that were skipped in Rakefile, and fixes the tests to pass

Includes skipped tests

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Update Shopify API to version 10.

Packaging for release 19.0.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb

- Update Shopify API to version 10.0.3
- Updates changelog and version to 19.0.2

Packaging for release 19.0.2

---

docs/Upgrading.md

@larry-perry recently had some issues upgrading their app to v19, because we no longer store the user in the session, but just the shopify user id, since we're relying on the library for the session state now.
This PR just adds a note to the upgrade guide to v19 to remind folks to update their references to prevent things from breaking.
(Also, sorry, my editor went a bit rogue applying our linting rules on the file, hope that's ok 😅 )

Add note about user id in session to upgrade guide

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json
test/shopify_app/session/jwt_test.rb

Sets up for publishing v19.1.0 which introduces:
- App billing support
- `login_callback_url` setting to override the default
- Special headers indicating where to redirect for OAuth when we return a 401 due to a missing or expired session

Packaging for release 19.1.0

---

Gemfile.lock
lib/shopify_app/version.rb
package.json

Attempting to package 20.0.2 once again as I lost some updates while rebasing my previous PR https://github.com/Shopify/shopify_app/pull/1462
Following this guide https://github.com/Shopify/shopify_app/blob/main/docs/Releasing.md. Hopefully this time I have include everything needed 🤞 

Packaging for release 20.0.2 (part 2)

---

README.md

Remove stale hiring link

---

service.yml

Action item from Services DB
Fixes https://github.com/Shopify/services/issues/3257
The classification is set in the Services DB UI (already completed for `shopify_app`) so it can safely be removed from `service.yml`.
**None are applicable**

Remove classification from service.yml

---

docs/Troubleshooting.md
docs/shopify_app/authentication.md

Adds clarifying docs on how to avoid common problems with `ShopifyApp::Authenticated` and App Bridge 3
Confirm docs are clear and accurate

Clarify `ShopifyApp::Authenticated` usage in docs

---

.github/workflows/stale.yml

We changed `days-before-issue-stale` and didn't change the message. Sorry I should have caught this earlier.
Is there anything else we want to change about the messaging?

Fix Stale Message

---

README.md

🔗 the new controller concern docs to the readme.

add link to controller concerns to readme

---

docs/Upgrading.md

Fix broken markdown link syntax

---

SECURITY.md

This change is a simple fix of a spelling mistake in the SECURITY.md file
No code change. Only a markdown file edit.
1. Nothing in particular. Fairly safe to merge. No code change.

Fix spelling of the word receive in the SECURITY.md

---

docs/Upgrading.md

Update v19 guidance

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb

packaging v12.3.0 for release

---

CONTRIBUTING.md

Encourages developers to write tests by providing the information needed to be successful in doing so in the CONTRIBUTING.md guide.

add test docs to the contributing docs

---

docs/shopify_app/authentication.md

Update docs to the Authentication page.
Links to the Github rendered page
- [Before](https://github.com/Shopify/shopify_app/blob/8df420a43ee0497dc7ecda4e5a98ab8f1a59d872/docs/shopify_app/authentication.md)
- [After](https://github.com/Shopify/shopify_app/blob/a7b286ac891a87933b8760cd3b6844eb4f6c853a/docs/shopify_app/authentication.md)

Update authentication page docs

---

CHANGELOG.md
Gemfile.lock
shopify_app.gemspec

Updating the shopify_api gem to latest ver

Bump shopify_api to 13.2

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

This PR set up release 21.8.1 of the gem

Package for release 21.8.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

Packaging for release 21.9.0

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

package for release 22.0.0

---

CHANGELOG.md
Gemfile.lock
shopify_app.gemspec

* Bumps `shopify_api` to v14.0.1
1. 
2. 
3. 

Bump shopify_api to version 14.0.1

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

- closes https://github.com/Shopify/develop-app-access/issues/315
Preparing of release 22.2.0

Packaging for release 22.2.0

---

README.md

Add post authenticate task docs to token exchange

---

README.md

Add clarification docs to prevent issues like these:
- https://github.com/Shopify/shopify_app/issues/1856#issuecomment-2156092219

Add docs on configuration details

---

CHANGELOG.md
Gemfile.lock
lib/shopify_app/version.rb
package.json

This PR sets up for the release of v22.3.1.

Packaging for release v22.3.1

---

README.md

[Docs] Update the Readme to include instructions for using the Shopify CLI
